# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\sourcecode\54\Eric6WorkSpace\module.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestModule(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(954, 523)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QPushButton {         \n"
"border-width: 2px 15px 2px 15px;\n"
"background-color:#2884D8;\n"
"color: #FFFFFF;\n"
"font-family: \"Verdana\";\n"
"font-size: 15px;\n"
"text-align: center;\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 951, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pagedisassemble = QtWidgets.QWidget()
        self.pagedisassemble.setObjectName("pagedisassemble")
        self.label_imageview = QtWidgets.QLabel(self.pagedisassemble)
        self.label_imageview.setGeometry(QtCore.QRect(10, 40, 811, 421))
        self.label_imageview.setText("")
        self.label_imageview.setPixmap(QtGui.QPixmap("../54AppTest/1.png"))
        self.label_imageview.setScaledContents(True)
        self.label_imageview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imageview.setObjectName("label_imageview")
        self.pushButton_disassemble_previous = QtWidgets.QPushButton(self.pagedisassemble)
        self.pushButton_disassemble_previous.setGeometry(QtCore.QRect(850, 50, 91, 31))
        self.pushButton_disassemble_previous.setObjectName("pushButton_disassemble_previous")
        self.pushButton_disassemble_next = QtWidgets.QPushButton(self.pagedisassemble)
        self.pushButton_disassemble_next.setGeometry(QtCore.QRect(850, 90, 91, 31))
        self.pushButton_disassemble_next.setObjectName("pushButton_disassemble_next")
        self.stackedWidget.addWidget(self.pagedisassemble)
        self.pageTestPrepare = QtWidgets.QWidget()
        self.pageTestPrepare.setObjectName("pageTestPrepare")
        self.pushButton_testprepare_verify = QtWidgets.QPushButton(self.pageTestPrepare)
        self.pushButton_testprepare_verify.setGeometry(QtCore.QRect(840, 350, 91, 31))
        self.pushButton_testprepare_verify.setObjectName("pushButton_testprepare_verify")
        self.label_testprepare_imageview = QtWidgets.QLabel(self.pageTestPrepare)
        self.label_testprepare_imageview.setGeometry(QtCore.QRect(20, 40, 571, 161))
        self.label_testprepare_imageview.setText("")
        self.label_testprepare_imageview.setObjectName("label_testprepare_imageview")
        self.groupBox_2 = QtWidgets.QGroupBox(self.pageTestPrepare)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 811, 381))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_result = QtWidgets.QTableWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_result.setFont(font)
        self.tableWidget_result.setStyleSheet("color:#666666")
        self.tableWidget_result.setObjectName("tableWidget_result")
        self.tableWidget_result.setColumnCount(5)
        self.tableWidget_result.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_result.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_result.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_result.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_result.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.tableWidget_result.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_result.setItem(5, 4, item)
        self.gridLayout_5.addWidget(self.tableWidget_result, 0, 0, 1, 1)
        self.pushButton_testprepare_config = QtWidgets.QPushButton(self.pageTestPrepare)
        self.pushButton_testprepare_config.setGeometry(QtCore.QRect(840, 290, 91, 31))
        self.pushButton_testprepare_config.setObjectName("pushButton_testprepare_config")
        self.stackedWidget.addWidget(self.pageTestPrepare)
        self.pageTestExecute = QtWidgets.QWidget()
        self.pageTestExecute.setObjectName("pageTestExecute")
        self.groupBox_3 = QtWidgets.QGroupBox(self.pageTestExecute)
        self.groupBox_3.setGeometry(QtCore.QRect(659, 10, 281, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowser_TestExecute_dataviewer = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_TestExecute_dataviewer.sizePolicy().hasHeightForWidth())
        self.textBrowser_TestExecute_dataviewer.setSizePolicy(sizePolicy)
        self.textBrowser_TestExecute_dataviewer.setMinimumSize(QtCore.QSize(100, 0))
        self.textBrowser_TestExecute_dataviewer.setStyleSheet("background-color: rgb(220, 240, 220);")
        self.textBrowser_TestExecute_dataviewer.setObjectName("textBrowser_TestExecute_dataviewer")
        self.gridLayout_4.addWidget(self.textBrowser_TestExecute_dataviewer, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_TestExecute_cleardata = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_cleardata.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_cleardata.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_cleardata.setObjectName("pushButton_TestExecute_cleardata")
        self.gridLayout_4.addWidget(self.pushButton_TestExecute_cleardata, 1, 1, 1, 1)
        self.pushButton_TestExecute_savedata = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_savedata.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_savedata.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_savedata.setObjectName("pushButton_TestExecute_savedata")
        self.gridLayout_4.addWidget(self.pushButton_TestExecute_savedata, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.pageTestExecute)
        self.groupBox.setGeometry(QtCore.QRect(20, 360, 621, 109))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 109))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_result_site2_29 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_29.sizePolicy().hasHeightForWidth())
        self.label_result_site2_29.setSizePolicy(sizePolicy)
        self.label_result_site2_29.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_29.setFont(font)
        self.label_result_site2_29.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_29.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_29.setScaledContents(False)
        self.label_result_site2_29.setObjectName("label_result_site2_29")
        self.gridLayout_8.addWidget(self.label_result_site2_29, 3, 1, 1, 1)
        self.label_result_site2_32 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_32.sizePolicy().hasHeightForWidth())
        self.label_result_site2_32.setSizePolicy(sizePolicy)
        self.label_result_site2_32.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_32.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_32.setFont(font)
        self.label_result_site2_32.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_32.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_32.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_32.setScaledContents(False)
        self.label_result_site2_32.setObjectName("label_result_site2_32")
        self.gridLayout_8.addWidget(self.label_result_site2_32, 3, 7, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setObjectName("label_33")
        self.gridLayout_8.addWidget(self.label_33, 3, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 3, 4, 1, 1)
        self.label_result_site2_31 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_31.sizePolicy().hasHeightForWidth())
        self.label_result_site2_31.setSizePolicy(sizePolicy)
        self.label_result_site2_31.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_31.setFont(font)
        self.label_result_site2_31.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_31.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_31.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_31.setScaledContents(False)
        self.label_result_site2_31.setObjectName("label_result_site2_31")
        self.gridLayout_8.addWidget(self.label_result_site2_31, 3, 5, 1, 1)
        self.label_result_site2_30 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_30.sizePolicy().hasHeightForWidth())
        self.label_result_site2_30.setSizePolicy(sizePolicy)
        self.label_result_site2_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_30.setFont(font)
        self.label_result_site2_30.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_result_site2_30.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_30.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_30.setScaledContents(False)
        self.label_result_site2_30.setObjectName("label_result_site2_30")
        self.gridLayout_8.addWidget(self.label_result_site2_30, 3, 3, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setObjectName("label_36")
        self.gridLayout_8.addWidget(self.label_36, 3, 6, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setObjectName("label_34")
        self.gridLayout_8.addWidget(self.label_34, 3, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 6, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 1, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_result_site2_24 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_24.sizePolicy().hasHeightForWidth())
        self.label_result_site2_24.setSizePolicy(sizePolicy)
        self.label_result_site2_24.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_24.setFont(font)
        self.label_result_site2_24.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_24.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_24.setScaledContents(False)
        self.label_result_site2_24.setObjectName("label_result_site2_24")
        self.gridLayout_8.addWidget(self.label_result_site2_24, 1, 7, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_result_site2_20 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_20.sizePolicy().hasHeightForWidth())
        self.label_result_site2_20.setSizePolicy(sizePolicy)
        self.label_result_site2_20.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_20.setFont(font)
        self.label_result_site2_20.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_20.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_20.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_20.setScaledContents(False)
        self.label_result_site2_20.setObjectName("label_result_site2_20")
        self.gridLayout_8.addWidget(self.label_result_site2_20, 0, 7, 1, 1)
        self.label_result_site2_19 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_19.sizePolicy().hasHeightForWidth())
        self.label_result_site2_19.setSizePolicy(sizePolicy)
        self.label_result_site2_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_19.setFont(font)
        self.label_result_site2_19.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_19.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_19.setScaledContents(False)
        self.label_result_site2_19.setObjectName("label_result_site2_19")
        self.gridLayout_8.addWidget(self.label_result_site2_19, 0, 5, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_result_site2_21 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_21.sizePolicy().hasHeightForWidth())
        self.label_result_site2_21.setSizePolicy(sizePolicy)
        self.label_result_site2_21.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_21.setFont(font)
        self.label_result_site2_21.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_21.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_21.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_21.setScaledContents(False)
        self.label_result_site2_21.setObjectName("label_result_site2_21")
        self.gridLayout_8.addWidget(self.label_result_site2_21, 1, 1, 1, 1)
        self.label_result_site2_17 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_17.sizePolicy().hasHeightForWidth())
        self.label_result_site2_17.setSizePolicy(sizePolicy)
        self.label_result_site2_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_17.setFont(font)
        self.label_result_site2_17.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_17.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_17.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_17.setScaledContents(False)
        self.label_result_site2_17.setObjectName("label_result_site2_17")
        self.gridLayout_8.addWidget(self.label_result_site2_17, 0, 1, 1, 1)
        self.label_result_site2_22 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_22.sizePolicy().hasHeightForWidth())
        self.label_result_site2_22.setSizePolicy(sizePolicy)
        self.label_result_site2_22.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_22.setFont(font)
        self.label_result_site2_22.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_result_site2_22.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_22.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_22.setScaledContents(False)
        self.label_result_site2_22.setObjectName("label_result_site2_22")
        self.gridLayout_8.addWidget(self.label_result_site2_22, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 1, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_result_site2_18 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_18.sizePolicy().hasHeightForWidth())
        self.label_result_site2_18.setSizePolicy(sizePolicy)
        self.label_result_site2_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_18.setFont(font)
        self.label_result_site2_18.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_result_site2_18.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_18.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_18.setScaledContents(False)
        self.label_result_site2_18.setObjectName("label_result_site2_18")
        self.gridLayout_8.addWidget(self.label_result_site2_18, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 1, 4, 1, 1)
        self.label_result_site2_23 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_23.sizePolicy().hasHeightForWidth())
        self.label_result_site2_23.setSizePolicy(sizePolicy)
        self.label_result_site2_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_23.setFont(font)
        self.label_result_site2_23.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_23.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_23.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_23.setScaledContents(False)
        self.label_result_site2_23.setObjectName("label_result_site2_23")
        self.gridLayout_8.addWidget(self.label_result_site2_23, 1, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setObjectName("label_32")
        self.gridLayout_8.addWidget(self.label_32, 2, 6, 1, 1)
        self.label_result_site2_27 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_27.sizePolicy().hasHeightForWidth())
        self.label_result_site2_27.setSizePolicy(sizePolicy)
        self.label_result_site2_27.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_27.setFont(font)
        self.label_result_site2_27.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_27.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_27.setScaledContents(False)
        self.label_result_site2_27.setObjectName("label_result_site2_27")
        self.gridLayout_8.addWidget(self.label_result_site2_27, 2, 5, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 2, 4, 1, 1)
        self.label_result_site2_25 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_25.sizePolicy().hasHeightForWidth())
        self.label_result_site2_25.setSizePolicy(sizePolicy)
        self.label_result_site2_25.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_25.setFont(font)
        self.label_result_site2_25.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_25.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_25.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_25.setScaledContents(False)
        self.label_result_site2_25.setObjectName("label_result_site2_25")
        self.gridLayout_8.addWidget(self.label_result_site2_25, 2, 1, 1, 1)
        self.label_result_site2_26 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_26.sizePolicy().hasHeightForWidth())
        self.label_result_site2_26.setSizePolicy(sizePolicy)
        self.label_result_site2_26.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_26.setFont(font)
        self.label_result_site2_26.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_result_site2_26.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_26.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_26.setScaledContents(False)
        self.label_result_site2_26.setObjectName("label_result_site2_26")
        self.gridLayout_8.addWidget(self.label_result_site2_26, 2, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 2, 2, 1, 1)
        self.label_result_site2_28 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_result_site2_28.sizePolicy().hasHeightForWidth())
        self.label_result_site2_28.setSizePolicy(sizePolicy)
        self.label_result_site2_28.setMinimumSize(QtCore.QSize(0, 0))
        self.label_result_site2_28.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        self.label_result_site2_28.setFont(font)
        self.label_result_site2_28.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_result_site2_28.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_result_site2_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_result_site2_28.setTextFormat(QtCore.Qt.AutoText)
        self.label_result_site2_28.setScaledContents(False)
        self.label_result_site2_28.setObjectName("label_result_site2_28")
        self.gridLayout_8.addWidget(self.label_result_site2_28, 2, 7, 1, 1)
        self.groupBox_127 = QtWidgets.QGroupBox(self.pageTestExecute)
        self.groupBox_127.setGeometry(QtCore.QRect(20, 10, 621, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_127.sizePolicy().hasHeightForWidth())
        self.groupBox_127.setSizePolicy(sizePolicy)
        self.groupBox_127.setMaximumSize(QtCore.QSize(16777215, 8000000))
        self.groupBox_127.setTitle("")
        self.groupBox_127.setObjectName("groupBox_127")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_127)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget_test = QtWidgets.QStackedWidget(self.groupBox_127)
        self.stackedWidget_test.setObjectName("stackedWidget_test")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.page_2)
        self.textEdit.setMaximumSize(QtCore.QSize(580, 16777215))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(339, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 0, 1, 1)
        self.pushButton_TestExecute_pre1 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_pre1.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_pre1.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_pre1.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/arrow-left-double-3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TestExecute_pre1.setIcon(icon)
        self.pushButton_TestExecute_pre1.setObjectName("pushButton_TestExecute_pre1")
        self.gridLayout_9.addWidget(self.pushButton_TestExecute_pre1, 0, 1, 1, 1)
        self.pushButton_TestExecute_do1 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_do1.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_do1.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_do1.setMinimumSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/arrow-right-3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TestExecute_do1.setIcon(icon1)
        self.pushButton_TestExecute_do1.setObjectName("pushButton_TestExecute_do1")
        self.gridLayout_9.addWidget(self.pushButton_TestExecute_do1, 0, 2, 1, 1)
        self.pushButton_TestExecute_next1 = QtWidgets.QPushButton(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_next1.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_next1.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_next1.setMinimumSize(QtCore.QSize(0, 0))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/arrow-right-double-3.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_TestExecute_next1.setIcon(icon2)
        self.pushButton_TestExecute_next1.setObjectName("pushButton_TestExecute_next1")
        self.gridLayout_9.addWidget(self.pushButton_TestExecute_next1, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.stackedWidget_test.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout_6.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(339, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem2, 0, 0, 1, 1)
        self.pushButton_TestExecute_pre2 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_pre2.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_pre2.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_pre2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_pre2.setIcon(icon)
        self.pushButton_TestExecute_pre2.setObjectName("pushButton_TestExecute_pre2")
        self.gridLayout_12.addWidget(self.pushButton_TestExecute_pre2, 0, 1, 1, 1)
        self.pushButton_TestExecute_do2 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_do2.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_do2.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_do2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_do2.setIcon(icon1)
        self.pushButton_TestExecute_do2.setObjectName("pushButton_TestExecute_do2")
        self.gridLayout_12.addWidget(self.pushButton_TestExecute_do2, 0, 2, 1, 1)
        self.pushButton_TestExecute_next2 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_next2.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_next2.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_next2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_next2.setIcon(icon2)
        self.pushButton_TestExecute_next2.setObjectName("pushButton_TestExecute_next2")
        self.gridLayout_12.addWidget(self.pushButton_TestExecute_next2, 0, 3, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.stackedWidget_test.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.textEdit_3 = QtWidgets.QTextEdit(self.page_4)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_13.addWidget(self.textEdit_3, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(339, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 0, 0, 1, 1)
        self.pushButton_TestExecute_pre3 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_pre3.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_pre3.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_pre3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_pre3.setIcon(icon)
        self.pushButton_TestExecute_pre3.setObjectName("pushButton_TestExecute_pre3")
        self.gridLayout_10.addWidget(self.pushButton_TestExecute_pre3, 0, 1, 1, 1)
        self.pushButton_TestExecute_do3 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_do3.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_do3.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_do3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_do3.setIcon(icon1)
        self.pushButton_TestExecute_do3.setObjectName("pushButton_TestExecute_do3")
        self.gridLayout_10.addWidget(self.pushButton_TestExecute_do3, 0, 2, 1, 1)
        self.pushButton_TestExecute_next3 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_next3.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_next3.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_next3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_next3.setIcon(icon2)
        self.pushButton_TestExecute_next3.setObjectName("pushButton_TestExecute_next3")
        self.gridLayout_10.addWidget(self.pushButton_TestExecute_next3, 0, 3, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.stackedWidget_test.addWidget(self.page_4)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.textEdit_4 = QtWidgets.QTextEdit(self.page_7)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_14.addWidget(self.textEdit_4, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(339, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 0, 0, 1, 1)
        self.pushButton_TestExecute_pre4 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_pre4.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_pre4.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_pre4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_pre4.setIcon(icon)
        self.pushButton_TestExecute_pre4.setObjectName("pushButton_TestExecute_pre4")
        self.gridLayout_11.addWidget(self.pushButton_TestExecute_pre4, 0, 1, 1, 1)
        self.pushButton_TestExecute_do4 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_do4.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_do4.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_do4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_do4.setIcon(icon1)
        self.pushButton_TestExecute_do4.setObjectName("pushButton_TestExecute_do4")
        self.gridLayout_11.addWidget(self.pushButton_TestExecute_do4, 0, 2, 1, 1)
        self.pushButton_TestExecute_next4 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_next4.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_next4.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_next4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_next4.setIcon(icon2)
        self.pushButton_TestExecute_next4.setObjectName("pushButton_TestExecute_next4")
        self.gridLayout_11.addWidget(self.pushButton_TestExecute_next4, 0, 3, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_8, 1, 0, 1, 1)
        self.stackedWidget_test.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.textEdit_5 = QtWidgets.QTextEdit(self.page_8)
        self.textEdit_5.setObjectName("textEdit_5")
        self.gridLayout_15.addWidget(self.textEdit_5, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem5 = QtWidgets.QSpacerItem(339, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem5, 0, 0, 1, 1)
        self.pushButton_TestExecute_pre5 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_pre5.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_pre5.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_pre5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_pre5.setIcon(icon)
        self.pushButton_TestExecute_pre5.setObjectName("pushButton_TestExecute_pre5")
        self.gridLayout_16.addWidget(self.pushButton_TestExecute_pre5, 0, 1, 1, 1)
        self.pushButton_TestExecute_do5 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_do5.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_do5.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_do5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_do5.setIcon(icon1)
        self.pushButton_TestExecute_do5.setObjectName("pushButton_TestExecute_do5")
        self.gridLayout_16.addWidget(self.pushButton_TestExecute_do5, 0, 2, 1, 1)
        self.pushButton_TestExecute_next5 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TestExecute_next5.sizePolicy().hasHeightForWidth())
        self.pushButton_TestExecute_next5.setSizePolicy(sizePolicy)
        self.pushButton_TestExecute_next5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_TestExecute_next5.setIcon(icon2)
        self.pushButton_TestExecute_next5.setObjectName("pushButton_TestExecute_next5")
        self.gridLayout_16.addWidget(self.pushButton_TestExecute_next5, 0, 3, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_9, 1, 0, 1, 1)
        self.stackedWidget_test.addWidget(self.page_8)
        self.gridLayout_3.addWidget(self.stackedWidget_test, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageTestExecute)
        self.pageTestData = QtWidgets.QWidget()
        self.pageTestData.setObjectName("pageTestData")
        self.groupBox_10 = QtWidgets.QGroupBox(self.pageTestData)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 10, 801, 451))
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_10.setStyleSheet("font-size:14px;\n"
"font-family:Microsoft YaHei;\n"
"")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_17.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_17.setSpacing(2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.tableWidget_results_site1 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_results_site1.setMinimumSize(QtCore.QSize(250, 0))
        self.tableWidget_results_site1.setObjectName("tableWidget_results_site1")
        self.tableWidget_results_site1.setColumnCount(0)
        self.tableWidget_results_site1.setRowCount(0)
        self.gridLayout_17.addWidget(self.tableWidget_results_site1, 0, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_18.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_18.setSpacing(2)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_37 = QtWidgets.QLabel(self.groupBox_11)
        self.label_37.setObjectName("label_37")
        self.gridLayout_18.addWidget(self.label_37, 0, 0, 1, 1)
        self.lcdNumber_total_site1 = QtWidgets.QLCDNumber(self.groupBox_11)
        self.lcdNumber_total_site1.setObjectName("lcdNumber_total_site1")
        self.gridLayout_18.addWidget(self.lcdNumber_total_site1, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_11)
        self.label_38.setObjectName("label_38")
        self.gridLayout_18.addWidget(self.label_38, 1, 0, 1, 1)
        self.lcdNumber_number_site1 = QtWidgets.QLCDNumber(self.groupBox_11)
        self.lcdNumber_number_site1.setObjectName("lcdNumber_number_site1")
        self.gridLayout_18.addWidget(self.lcdNumber_number_site1, 1, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_11)
        self.label_39.setObjectName("label_39")
        self.gridLayout_18.addWidget(self.label_39, 2, 0, 1, 1)
        self.lcdNumber_rates_site1 = QtWidgets.QLCDNumber(self.groupBox_11)
        self.lcdNumber_rates_site1.setObjectName("lcdNumber_rates_site1")
        self.gridLayout_18.addWidget(self.lcdNumber_rates_site1, 2, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.tableWidget_results_site2 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_results_site2.setObjectName("tableWidget_results_site2")
        self.tableWidget_results_site2.setColumnCount(0)
        self.tableWidget_results_site2.setRowCount(0)
        self.gridLayout_17.addWidget(self.tableWidget_results_site2, 1, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_19.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_19.setSpacing(2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_40 = QtWidgets.QLabel(self.groupBox_13)
        self.label_40.setObjectName("label_40")
        self.gridLayout_19.addWidget(self.label_40, 0, 0, 1, 1)
        self.lcdNumber_total_site2 = QtWidgets.QLCDNumber(self.groupBox_13)
        self.lcdNumber_total_site2.setObjectName("lcdNumber_total_site2")
        self.gridLayout_19.addWidget(self.lcdNumber_total_site2, 0, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox_13)
        self.label_41.setObjectName("label_41")
        self.gridLayout_19.addWidget(self.label_41, 1, 0, 1, 1)
        self.lcdNumber_number_site2 = QtWidgets.QLCDNumber(self.groupBox_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_number_site2.setFont(font)
        self.lcdNumber_number_site2.setObjectName("lcdNumber_number_site2")
        self.gridLayout_19.addWidget(self.lcdNumber_number_site2, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_13)
        self.label_42.setObjectName("label_42")
        self.gridLayout_19.addWidget(self.label_42, 2, 0, 1, 1)
        self.lcdNumber_rates_site2 = QtWidgets.QLCDNumber(self.groupBox_13)
        self.lcdNumber_rates_site2.setObjectName("lcdNumber_rates_site2")
        self.gridLayout_19.addWidget(self.lcdNumber_rates_site2, 2, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_13, 1, 1, 1, 1)
        self.tableWidget_results_site3 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_results_site3.setObjectName("tableWidget_results_site3")
        self.tableWidget_results_site3.setColumnCount(0)
        self.tableWidget_results_site3.setRowCount(0)
        self.gridLayout_17.addWidget(self.tableWidget_results_site3, 2, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_20.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_20.setSpacing(2)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_43 = QtWidgets.QLabel(self.groupBox_14)
        self.label_43.setObjectName("label_43")
        self.gridLayout_20.addWidget(self.label_43, 0, 0, 1, 1)
        self.lcdNumber_total_site3 = QtWidgets.QLCDNumber(self.groupBox_14)
        self.lcdNumber_total_site3.setObjectName("lcdNumber_total_site3")
        self.gridLayout_20.addWidget(self.lcdNumber_total_site3, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_14)
        self.label_44.setObjectName("label_44")
        self.gridLayout_20.addWidget(self.label_44, 1, 0, 1, 1)
        self.lcdNumber_number_site3 = QtWidgets.QLCDNumber(self.groupBox_14)
        self.lcdNumber_number_site3.setObjectName("lcdNumber_number_site3")
        self.gridLayout_20.addWidget(self.lcdNumber_number_site3, 1, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_14)
        self.label_45.setObjectName("label_45")
        self.gridLayout_20.addWidget(self.label_45, 2, 0, 1, 1)
        self.lcdNumber_rates_site3 = QtWidgets.QLCDNumber(self.groupBox_14)
        self.lcdNumber_rates_site3.setObjectName("lcdNumber_rates_site3")
        self.gridLayout_20.addWidget(self.lcdNumber_rates_site3, 2, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_14, 2, 1, 1, 1)
        self.tableWidget_results_site4 = QtWidgets.QTableWidget(self.groupBox_10)
        self.tableWidget_results_site4.setObjectName("tableWidget_results_site4")
        self.tableWidget_results_site4.setColumnCount(0)
        self.tableWidget_results_site4.setRowCount(0)
        self.gridLayout_17.addWidget(self.tableWidget_results_site4, 3, 0, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout_21.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_21.setSpacing(2)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_46 = QtWidgets.QLabel(self.groupBox_15)
        self.label_46.setObjectName("label_46")
        self.gridLayout_21.addWidget(self.label_46, 0, 0, 1, 1)
        self.lcdNumber_total_site4 = QtWidgets.QLCDNumber(self.groupBox_15)
        self.lcdNumber_total_site4.setObjectName("lcdNumber_total_site4")
        self.gridLayout_21.addWidget(self.lcdNumber_total_site4, 0, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_15)
        self.label_47.setObjectName("label_47")
        self.gridLayout_21.addWidget(self.label_47, 1, 0, 1, 1)
        self.lcdNumber_number_site4 = QtWidgets.QLCDNumber(self.groupBox_15)
        self.lcdNumber_number_site4.setObjectName("lcdNumber_number_site4")
        self.gridLayout_21.addWidget(self.lcdNumber_number_site4, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_15)
        self.label_48.setObjectName("label_48")
        self.gridLayout_21.addWidget(self.label_48, 2, 0, 1, 1)
        self.lcdNumber_rates_site4 = QtWidgets.QLCDNumber(self.groupBox_15)
        self.lcdNumber_rates_site4.setObjectName("lcdNumber_rates_site4")
        self.gridLayout_21.addWidget(self.lcdNumber_rates_site4, 2, 1, 1, 1)
        self.gridLayout_17.addWidget(self.groupBox_15, 3, 1, 1, 1)
        self.pushButton_TestData_export = QtWidgets.QPushButton(self.pageTestData)
        self.pushButton_TestData_export.setGeometry(QtCore.QRect(820, 70, 111, 31))
        self.pushButton_TestData_export.setObjectName("pushButton_TestData_export")
        self.pushButton_TestData_upload = QtWidgets.QPushButton(self.pageTestData)
        self.pushButton_TestData_upload.setGeometry(QtCore.QRect(820, 120, 111, 31))
        self.pushButton_TestData_upload.setObjectName("pushButton_TestData_upload")
        self.stackedWidget.addWidget(self.pageTestData)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.pushButton_last = QtWidgets.QPushButton(Dialog)
        self.pushButton_last.setGeometry(QtCore.QRect(811, 1, 44, 39))
        self.pushButton_last.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.pushButton_last.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/icon/last4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last.setIcon(icon3)
        self.pushButton_last.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_last.setObjectName("pushButton_last")
        self.pushButton_next = QtWidgets.QPushButton(Dialog)
        self.pushButton_next.setGeometry(QtCore.QRect(861, 1, 44, 39))
        self.pushButton_next.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_next.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/icon/next4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon4)
        self.pushButton_next.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(910, 1, 44, 39))
        self.pushButton_close.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/icon/close4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon5)
        self.pushButton_close.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_close.setObjectName("pushButton_close")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.label_test_steps = QtWidgets.QLabel(Dialog)
        self.label_test_steps.setGeometry(QtCore.QRect(110, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_test_steps.setFont(font)
        self.label_test_steps.setTextFormat(QtCore.Qt.PlainText)
        self.label_test_steps.setObjectName("label_test_steps")

        self.retranslateUi(Dialog)
        self.stackedWidget_test.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_disassemble_previous.setText(_translate("Dialog", "上一步"))
        self.pushButton_disassemble_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testprepare_verify.setText(_translate("Dialog", "确认"))
        self.groupBox_2.setTitle(_translate("Dialog", "测试仪表"))
        item = self.tableWidget_result.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "序号"))
        item = self.tableWidget_result.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "名称"))
        item = self.tableWidget_result.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "类型"))
        item = self.tableWidget_result.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "编号/型号"))
        item = self.tableWidget_result.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "数量"))
        __sortingEnabled = self.tableWidget_result.isSortingEnabled()
        self.tableWidget_result.setSortingEnabled(False)
        item = self.tableWidget_result.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_result.item(0, 1)
        item.setText(_translate("Dialog", "矢量信号源"))
        item = self.tableWidget_result.item(0, 2)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_result.item(0, 3)
        item.setText(_translate("Dialog", "R&S SMW200"))
        item = self.tableWidget_result.item(0, 4)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_result.item(1, 0)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_result.item(1, 1)
        item.setText(_translate("Dialog", "频谱仪"))
        item = self.tableWidget_result.item(1, 2)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_result.item(1, 3)
        item.setText(_translate("Dialog", "R&S FSW50"))
        item = self.tableWidget_result.item(1, 4)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_result.item(2, 0)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_result.item(2, 1)
        item.setText(_translate("Dialog", "功率计"))
        item = self.tableWidget_result.item(2, 2)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_result.item(2, 3)
        item.setText(_translate("Dialog", "R&S NRX"))
        item = self.tableWidget_result.item(2, 4)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_result.item(3, 0)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_result.item(3, 1)
        item.setText(_translate("Dialog", "射频连接器"))
        item = self.tableWidget_result.item(3, 2)
        item.setText(_translate("Dialog", "附件"))
        item = self.tableWidget_result.item(3, 4)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget_result.item(4, 0)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_result.item(4, 1)
        item.setText(_translate("Dialog", "网线"))
        item = self.tableWidget_result.item(4, 2)
        item.setText(_translate("Dialog", "附件"))
        item = self.tableWidget_result.item(4, 4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_result.item(5, 0)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget_result.item(5, 1)
        item.setText(_translate("Dialog", "射频线缆"))
        item = self.tableWidget_result.item(5, 2)
        item.setText(_translate("Dialog", "附件"))
        item = self.tableWidget_result.item(5, 4)
        item.setText(_translate("Dialog", "5"))
        self.tableWidget_result.setSortingEnabled(__sortingEnabled)
        self.pushButton_testprepare_config.setText(_translate("Dialog", "配置"))
        self.groupBox_3.setTitle(_translate("Dialog", "测试日志"))
        self.textBrowser_TestExecute_dataviewer.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'宋体\'; font-size:11pt;\">test start</span></p></body></html>"))
        self.pushButton_TestExecute_cleardata.setText(_translate("Dialog", "Clear"))
        self.pushButton_TestExecute_savedata.setText(_translate("Dialog", "Save"))
        self.groupBox.setTitle(_translate("Dialog", "Results"))
        self.label_result_site2_29.setText(_translate("Dialog", "PASS"))
        self.label_result_site2_32.setText(_translate("Dialog", "PASS"))
        self.label_33.setText(_translate("Dialog", "LAN41"))
        self.label_35.setText(_translate("Dialog", "LAN12"))
        self.label_result_site2_31.setText(_translate("Dialog", "PASS"))
        self.label_result_site2_30.setText(_translate("Dialog", "FAIL"))
        self.label_36.setText(_translate("Dialog", "LAN16"))
        self.label_34.setText(_translate("Dialog", "LAN8"))
        self.label_23.setText(_translate("Dialog", "LAN9"))
        self.label_24.setText(_translate("Dialog", "LAN13"))
        self.label_28.setText(_translate("Dialog", "LAN14"))
        self.label_20.setText(_translate("Dialog", "LAN1"))
        self.label_result_site2_24.setText(_translate("Dialog", "PASS"))
        self.label_29.setText(_translate("Dialog", "LAN3"))
        self.label_result_site2_20.setText(_translate("Dialog", "PASS"))
        self.label_result_site2_19.setText(_translate("Dialog", "PASS"))
        self.label_25.setText(_translate("Dialog", "LAN2"))
        self.label_result_site2_21.setText(_translate("Dialog", "PASS"))
        self.label_result_site2_17.setText(_translate("Dialog", "PASS"))
        self.label_result_site2_22.setText(_translate("Dialog", "FAIL"))
        self.label_26.setText(_translate("Dialog", "LAN6"))
        self.label_22.setText(_translate("Dialog", "LAN5"))
        self.label_result_site2_18.setText(_translate("Dialog", "FAIL"))
        self.label_27.setText(_translate("Dialog", "LAN10"))
        self.label_result_site2_23.setText(_translate("Dialog", "PASS"))
        self.label_32.setText(_translate("Dialog", "LAN15"))
        self.label_result_site2_27.setText(_translate("Dialog", "PASS"))
        self.label_31.setText(_translate("Dialog", "LAN11"))
        self.label_result_site2_25.setText(_translate("Dialog", "PASS"))
        self.label_result_site2_26.setText(_translate("Dialog", "FAIL"))
        self.label_30.setText(_translate("Dialog", "LAN7"))
        self.label_result_site2_28.setText(_translate("Dialog", "PASS"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icon/JHJ1.png\" /></p></body></html>"))
        self.groupBox_5.setTitle(_translate("Dialog", "Control"))
        self.pushButton_TestExecute_pre1.setText(_translate("Dialog", "pre"))
        self.pushButton_TestExecute_do1.setText(_translate("Dialog", "excute"))
        self.pushButton_TestExecute_next1.setText(_translate("Dialog", "next"))
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icon/JHJ2.png\" /></p></body></html>"))
        self.groupBox_6.setTitle(_translate("Dialog", "Control"))
        self.pushButton_TestExecute_pre2.setText(_translate("Dialog", "pre"))
        self.pushButton_TestExecute_do2.setText(_translate("Dialog", "excute"))
        self.pushButton_TestExecute_next2.setText(_translate("Dialog", "next"))
        self.textEdit_3.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icon/JHJ3.png\" /></p></body></html>"))
        self.groupBox_7.setTitle(_translate("Dialog", "Control"))
        self.pushButton_TestExecute_pre3.setText(_translate("Dialog", "pre"))
        self.pushButton_TestExecute_do3.setText(_translate("Dialog", "excute"))
        self.pushButton_TestExecute_next3.setText(_translate("Dialog", "next"))
        self.textEdit_4.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icon/JHJ4.png\" /></p></body></html>"))
        self.groupBox_8.setTitle(_translate("Dialog", "Control"))
        self.pushButton_TestExecute_pre4.setText(_translate("Dialog", "pre"))
        self.pushButton_TestExecute_do4.setText(_translate("Dialog", "excute"))
        self.pushButton_TestExecute_next4.setText(_translate("Dialog", "next"))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icon/JHJ5.png\" /></p></body></html>"))
        self.groupBox_9.setTitle(_translate("Dialog", "Control"))
        self.pushButton_TestExecute_pre5.setText(_translate("Dialog", "pre"))
        self.pushButton_TestExecute_do5.setText(_translate("Dialog", "excute"))
        self.pushButton_TestExecute_next5.setText(_translate("Dialog", "next"))
        self.groupBox_10.setTitle(_translate("Dialog", "测试结果"))
        self.groupBox_11.setTitle(_translate("Dialog", "site1"))
        self.label_37.setText(_translate("Dialog", "total"))
        self.label_38.setText(_translate("Dialog", "good number"))
        self.label_39.setText(_translate("Dialog", "good rates"))
        self.groupBox_13.setTitle(_translate("Dialog", "site2"))
        self.label_40.setText(_translate("Dialog", "total"))
        self.label_41.setText(_translate("Dialog", "good number"))
        self.label_42.setText(_translate("Dialog", "good rates"))
        self.groupBox_14.setTitle(_translate("Dialog", "site3"))
        self.label_43.setText(_translate("Dialog", "total"))
        self.label_44.setText(_translate("Dialog", "good number"))
        self.label_45.setText(_translate("Dialog", "good rates"))
        self.groupBox_15.setTitle(_translate("Dialog", "site4"))
        self.label_46.setText(_translate("Dialog", "total"))
        self.label_47.setText(_translate("Dialog", "good number"))
        self.label_48.setText(_translate("Dialog", "good rates"))
        self.pushButton_TestData_export.setText(_translate("Dialog", "数据导出"))
        self.pushButton_TestData_upload.setText(_translate("Dialog", "数据上传"))
        self.label_5.setText(_translate("Dialog", "测试步骤："))
        self.label_test_steps.setText(_translate("Dialog", "系统拆机"))
import res.iconQrc_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
