# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\tianheng_projects\54\54TestFramework\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 1024)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QGroupBox{\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei;\n"
"}\n"
"\n"
"QMainWindow::title{\n"
"background-color:rgb(0, 85, 255);\n"
"font-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxMenu = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxMenu.setGeometry(QtCore.QRect(0, 0, 261, 1021))
        self.groupBoxMenu.setStyleSheet("background-color:#D0DAE5;\n"
"color:#666666")
        self.groupBoxMenu.setObjectName("groupBoxMenu")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBoxMenu)
        self.treeWidget.setGeometry(QtCore.QRect(10, 20, 231, 971))
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 0, 1011, 1001))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:#D0DAE5;\n"
"color:#666666")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 991, 971))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FKJ通信维修分系统"))
        self.groupBoxMenu.setTitle(_translate("MainWindow", "测试模块"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "散射高频设备"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "收/发单元"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "低噪声放大器"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "功放"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "耦合器"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "自环器"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "滤波器"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "波导开关"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("MainWindow", "监控模块"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "散射低频设备"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "辅助复分接器"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "调制解调器器"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "中放AGC"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("MainWindow", "监控模块"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "散射天线控制设备"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "显示器"))
        self.treeWidget.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "键盘和信号灯"))
        self.treeWidget.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "PLC模块"))
        self.treeWidget.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "伺服控制模块"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "MW-1500微波电台"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "数字处理单元"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "收/发单元"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "LNA和射频自环器"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "功放单元"))
        self.treeWidget.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "显控单元"))
        self.treeWidget.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "EOW"))
        self.treeWidget.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "双工器"))
        self.treeWidget.topLevelItem(3).child(7).setText(0, _translate("MainWindow", "网络控制单元"))
        self.treeWidget.topLevelItem(3).child(8).setText(0, _translate("MainWindow", "天馈系统"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "交换机"))
        self.treeWidget.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "切换(交换)模块(主控板)"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "VHF电台"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "功放模块"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "滤波器模块"))
        self.treeWidget.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "调谐模块"))
        self.treeWidget.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "综合业务模块"))
        self.treeWidget.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "音频模块"))
        self.treeWidget.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "频率合成模块"))
        self.treeWidget.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "中频模块"))
        self.treeWidget.topLevelItem(6).setText(0, _translate("MainWindow", "自组网微波通信设备"))
        self.treeWidget.topLevelItem(6).child(0).setText(0, _translate("MainWindow", "协议处理和管理模块"))
        self.treeWidget.topLevelItem(6).child(1).setText(0, _translate("MainWindow", "室外单元"))
        self.treeWidget.topLevelItem(7).setText(0, _translate("MainWindow", "八端口光端机"))
        self.treeWidget.topLevelItem(7).child(0).setText(0, _translate("MainWindow", "数据处理和光接口模块"))
        self.treeWidget.topLevelItem(8).setText(0, _translate("MainWindow", "双端口光端机"))
        self.treeWidget.topLevelItem(8).child(0).setText(0, _translate("MainWindow", "数据处理和光接口模块"))
        self.treeWidget.topLevelItem(9).setText(0, _translate("MainWindow", "SDSL设备"))
        self.treeWidget.topLevelItem(9).child(0).setText(0, _translate("MainWindow", "数据和线路模块"))
        self.treeWidget.topLevelItem(10).setText(0, _translate("MainWindow", "IP调度话"))
        self.treeWidget.topLevelItem(10).child(0).setText(0, _translate("MainWindow", "调度模块"))
        self.treeWidget.topLevelItem(11).setText(0, _translate("MainWindow", "IP保密机"))
        self.treeWidget.topLevelItem(11).child(0).setText(0, _translate("MainWindow", "加密模块"))
        self.treeWidget.topLevelItem(12).setText(0, _translate("MainWindow", "防火墙"))
        self.treeWidget.topLevelItem(12).child(0).setText(0, _translate("MainWindow", "协议处理模块"))
        self.treeWidget.topLevelItem(13).setText(0, _translate("MainWindow", "语音网关"))
        self.treeWidget.topLevelItem(13).child(0).setText(0, _translate("MainWindow", "话音处理模块"))
        self.treeWidget.topLevelItem(14).setText(0, _translate("MainWindow", "通信控制设备"))
        self.treeWidget.topLevelItem(14).child(0).setText(0, _translate("MainWindow", "协议控制和转换模块"))
        self.treeWidget.topLevelItem(15).setText(0, _translate("MainWindow", "VHF车载对讲机"))
        self.treeWidget.topLevelItem(15).child(0).setText(0, _translate("MainWindow", "主机"))
        self.treeWidget.topLevelItem(15).child(1).setText(0, _translate("MainWindow", "话柄"))
        self.treeWidget.topLevelItem(16).setText(0, _translate("MainWindow", "路由器"))
        self.treeWidget.topLevelItem(16).child(0).setText(0, _translate("MainWindow", "路由模块"))
        self.treeWidget.topLevelItem(17).setText(0, _translate("MainWindow", "铷钟"))
        self.treeWidget.topLevelItem(17).child(0).setText(0, _translate("MainWindow", "铷原子钟频标模块"))
        self.treeWidget.topLevelItem(17).child(1).setText(0, _translate("MainWindow", "监控单元"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "测试项目"))
import res.iconQrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
