# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\autoTest\54testframework\ui\mw1500_device\mw1500_device.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 1024)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QDialog{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QTextBrower{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QWidget{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QStackedWidget{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QHeaderView{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size:12px;\n"
"font-family:Microsoft YaHei;\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QPushButton{         /*按钮自适应拉伸背景*/\n"
"border-width: 2px 15px 2px 15px;\n"
"background-color:#2884D8;\n"
"color: #FFFFFF;\n"
"font-size:12px;\n"
"font-family:Microsoft YaHei;\n"
"}\n"
"\n"
"QGroupBox{\n"
"font-size:12px;\n"
"font-family:Microsoft YaHei;\n"
"border:1px solid rgb(0, 0, 0); \n"
"}")
        self.gridLayout_8 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_start = QtWidgets.QPushButton(Dialog)
        self.pushButton_start.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.pushButton_start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon/start1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon)
        self.pushButton_start.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 0, 0, 1, 1)
        self.pushButton_restart = QtWidgets.QPushButton(Dialog)
        self.pushButton_restart.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_restart.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon/restart1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_restart.setIcon(icon1)
        self.pushButton_restart.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_restart.setObjectName("pushButton_restart")
        self.gridLayout.addWidget(self.pushButton_restart, 0, 1, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon/close1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon2)
        self.pushButton_close.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_test_modules = QtWidgets.QGroupBox(Dialog)
        self.groupBox_test_modules.setObjectName("groupBox_test_modules")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_test_modules)
        self.gridLayout_6.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_6.setVerticalSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_test_modules)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_test_duration = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.label_test_duration.setFont(font)
        self.label_test_duration.setText("")
        self.label_test_duration.setTextFormat(QtCore.Qt.PlainText)
        self.label_test_duration.setObjectName("label_test_duration")
        self.gridLayout_2.addWidget(self.label_test_duration, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_test_modules)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Checked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Checked)
        self.gridLayout_3.addWidget(self.treeWidget, 1, 0, 1, 1)
        self.gridLayout_3.setRowStretch(1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_test_modules)
        self.groupBox_test_resource = QtWidgets.QGroupBox(Dialog)
        self.groupBox_test_resource.setObjectName("groupBox_test_resource")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_test_resource)
        self.gridLayout_5.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tableWidget_test_resource = QtWidgets.QTableWidget(self.groupBox_test_resource)
        self.tableWidget_test_resource.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_test_resource.setObjectName("tableWidget_test_resource")
        self.tableWidget_test_resource.setColumnCount(4)
        self.tableWidget_test_resource.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(9, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(10, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(10, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(11, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(11, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(12, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(12, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(13, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(13, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(14, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(14, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(15, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_resource.setItem(15, 3, item)
        self.tableWidget_test_resource.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget_test_resource.horizontalHeader().setDefaultSectionSize(153)
        self.tableWidget_test_resource.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_test_resource.verticalHeader().setStretchLastSection(False)
        self.gridLayout_5.addWidget(self.tableWidget_test_resource, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_test_resource)
        self.horizontalLayout.setStretch(1, 2)
        self.gridLayout_8.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.groupBox_test_results = QtWidgets.QGroupBox(Dialog)
        self.groupBox_test_results.setTitle("")
        self.groupBox_test_results.setObjectName("groupBox_test_results")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_test_results)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_test_results)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_test_results_tr_t = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_test_results_tr_t.setObjectName("tableWidget_test_results_tr_t")
        self.tableWidget_test_results_tr_t.setColumnCount(4)
        self.tableWidget_test_results_tr_t.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_t.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_t.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_t.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_t.setHorizontalHeaderItem(3, item)
        self.tableWidget_test_results_tr_t.horizontalHeader().setDefaultSectionSize(228)
        self.gridLayout_4.addWidget(self.tableWidget_test_results_tr_t, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tableWidget_test_results_tr_r = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_test_results_tr_r.setObjectName("tableWidget_test_results_tr_r")
        self.tableWidget_test_results_tr_r.setColumnCount(4)
        self.tableWidget_test_results_tr_r.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_r.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_r.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_r.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_tr_r.setHorizontalHeaderItem(3, item)
        self.gridLayout_12.addWidget(self.tableWidget_test_results_tr_r, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidget_test_results_lna = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_test_results_lna.setObjectName("tableWidget_test_results_lna")
        self.tableWidget_test_results_lna.setColumnCount(4)
        self.tableWidget_test_results_lna.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_lna.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_lna.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_lna.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_lna.setHorizontalHeaderItem(3, item)
        self.tableWidget_test_results_lna.horizontalHeader().setDefaultSectionSize(228)
        self.gridLayout_9.addWidget(self.tableWidget_test_results_lna, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tableWidget_test_results_pa = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_test_results_pa.setObjectName("tableWidget_test_results_pa")
        self.tableWidget_test_results_pa.setColumnCount(4)
        self.tableWidget_test_results_pa.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_pa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_pa.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_pa.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_pa.setHorizontalHeaderItem(3, item)
        self.gridLayout_10.addWidget(self.tableWidget_test_results_pa, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget_test_results_sc = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_test_results_sc.setObjectName("tableWidget_test_results_sc")
        self.tableWidget_test_results_sc.setColumnCount(4)
        self.tableWidget_test_results_sc.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_sc.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_sc.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_sc.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_sc.setHorizontalHeaderItem(3, item)
        self.gridLayout_11.addWidget(self.tableWidget_test_results_sc, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tableWidget_test_results_wg = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_test_results_wg.setObjectName("tableWidget_test_results_wg")
        self.tableWidget_test_results_wg.setColumnCount(4)
        self.tableWidget_test_results_wg.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_wg.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_wg.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_wg.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_wg.setHorizontalHeaderItem(3, item)
        self.gridLayout_13.addWidget(self.tableWidget_test_results_wg, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tableWidget_test_results_coupler = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_test_results_coupler.setObjectName("tableWidget_test_results_coupler")
        self.tableWidget_test_results_coupler.setColumnCount(4)
        self.tableWidget_test_results_coupler.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_coupler.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_coupler.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_coupler.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_coupler.setHorizontalHeaderItem(3, item)
        self.gridLayout_14.addWidget(self.tableWidget_test_results_coupler, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tableWidget_test_results_monitor = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_test_results_monitor.setObjectName("tableWidget_test_results_monitor")
        self.tableWidget_test_results_monitor.setColumnCount(4)
        self.tableWidget_test_results_monitor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_monitor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_monitor.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_monitor.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_test_results_monitor.setHorizontalHeaderItem(3, item)
        self.gridLayout_15.addWidget(self.tableWidget_test_results_monitor, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_test_results, 2, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_4 = QtWidgets.QSplitter(Dialog)
        self.splitter_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_test_modules.setTitle(_translate("Dialog", "测试项目"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "1"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Dialog", "MW-1500微波通信设备"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Dialog", "收发信机单元/发信机"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Dialog", "收发信机单元/收信机"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("Dialog", "低噪声放大器"))
        self.treeWidget.topLevelItem(0).child(3).setText(0, _translate("Dialog", "耦合器"))
        self.treeWidget.topLevelItem(0).child(4).setText(0, _translate("Dialog", "自环器"))
        self.treeWidget.topLevelItem(0).child(5).setText(0, _translate("Dialog", "滤波器"))
        self.treeWidget.topLevelItem(0).child(6).setText(0, _translate("Dialog", "波导开关"))
        self.treeWidget.topLevelItem(0).child(7).setText(0, _translate("Dialog", "监控设备"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_test_resource.setTitle(_translate("Dialog", "测试资源"))
        item = self.tableWidget_test_resource.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_test_resource.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_test_resource.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_test_resource.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_test_resource.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_test_resource.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget_test_resource.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget_test_resource.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget_test_resource.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget_test_resource.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget_test_resource.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget_test_resource.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget_test_resource.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget_test_resource.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget_test_resource.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget_test_resource.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_test_resource.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "名称"))
        item = self.tableWidget_test_resource.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "类型"))
        item = self.tableWidget_test_resource.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "编号/型号"))
        item = self.tableWidget_test_resource.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "备注"))
        __sortingEnabled = self.tableWidget_test_resource.isSortingEnabled()
        self.tableWidget_test_resource.setSortingEnabled(False)
        item = self.tableWidget_test_resource.item(0, 0)
        item.setText(_translate("Dialog", "信号源"))
        item = self.tableWidget_test_resource.item(0, 1)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_test_resource.item(0, 2)
        item.setText(_translate("Dialog", "keysight E8257D"))
        item = self.tableWidget_test_resource.item(0, 3)
        item.setText(_translate("Dialog", "1台"))
        item = self.tableWidget_test_resource.item(1, 0)
        item.setText(_translate("Dialog", "频谱仪"))
        item = self.tableWidget_test_resource.item(1, 1)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_test_resource.item(1, 2)
        item.setText(_translate("Dialog", "keysight N9030B"))
        item = self.tableWidget_test_resource.item(1, 3)
        item.setText(_translate("Dialog", "1台"))
        item = self.tableWidget_test_resource.item(2, 0)
        item.setText(_translate("Dialog", "功率计"))
        item = self.tableWidget_test_resource.item(2, 1)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_test_resource.item(2, 2)
        item.setText(_translate("Dialog", "keysight N1911A"))
        item = self.tableWidget_test_resource.item(2, 3)
        item.setText(_translate("Dialog", "1台"))
        item = self.tableWidget_test_resource.item(3, 0)
        item.setText(_translate("Dialog", "万用表"))
        item = self.tableWidget_test_resource.item(3, 1)
        item.setText(_translate("Dialog", "仪器仪表"))
        item = self.tableWidget_test_resource.item(3, 2)
        item.setText(_translate("Dialog", "keysight DSOX3012A"))
        item = self.tableWidget_test_resource.item(3, 3)
        item.setText(_translate("Dialog", "1台"))
        item = self.tableWidget_test_resource.item(4, 0)
        item.setText(_translate("Dialog", "电源线"))
        item = self.tableWidget_test_resource.item(4, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(4, 2)
        item.setText(_translate("Dialog", "W001/220V"))
        item = self.tableWidget_test_resource.item(4, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(5, 0)
        item.setText(_translate("Dialog", "电源线"))
        item = self.tableWidget_test_resource.item(5, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(5, 2)
        item.setText(_translate("Dialog", "W002/数据线"))
        item = self.tableWidget_test_resource.item(5, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(6, 0)
        item.setText(_translate("Dialog", "射频电缆"))
        item = self.tableWidget_test_resource.item(6, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(6, 2)
        item.setText(_translate("Dialog", "W003/(N/SMA-J/J)"))
        item = self.tableWidget_test_resource.item(6, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(7, 0)
        item.setText(_translate("Dialog", "射频电缆"))
        item = self.tableWidget_test_resource.item(7, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(7, 2)
        item.setText(_translate("Dialog", "W004/(N/SMA-J/J)"))
        item = self.tableWidget_test_resource.item(7, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(8, 0)
        item.setText(_translate("Dialog", "射频电缆"))
        item = self.tableWidget_test_resource.item(8, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(8, 2)
        item.setText(_translate("Dialog", "W005/(SMA/SMA-J/J)"))
        item = self.tableWidget_test_resource.item(8, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(9, 0)
        item.setText(_translate("Dialog", "射频电缆"))
        item = self.tableWidget_test_resource.item(9, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(9, 2)
        item.setText(_translate("Dialog", "W006/(SMA/SMA-J/J)"))
        item = self.tableWidget_test_resource.item(9, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(10, 0)
        item.setText(_translate("Dialog", "射频电缆"))
        item = self.tableWidget_test_resource.item(10, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(10, 2)
        item.setText(_translate("Dialog", "W007/(N/N-J/J)"))
        item = self.tableWidget_test_resource.item(10, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(11, 0)
        item.setText(_translate("Dialog", "射频电缆"))
        item = self.tableWidget_test_resource.item(11, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(11, 2)
        item.setText(_translate("Dialog", "W008/(N/N-J/J)"))
        item = self.tableWidget_test_resource.item(11, 3)
        item.setText(_translate("Dialog", "2m，1根"))
        item = self.tableWidget_test_resource.item(12, 0)
        item.setText(_translate("Dialog", "测试台"))
        item = self.tableWidget_test_resource.item(12, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(12, 2)
        item.setText(_translate("Dialog", "TA001"))
        item = self.tableWidget_test_resource.item(12, 3)
        item.setText(_translate("Dialog", "1个"))
        item = self.tableWidget_test_resource.item(13, 0)
        item.setText(_translate("Dialog", "衰减器"))
        item = self.tableWidget_test_resource.item(13, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(13, 2)
        item.setText(_translate("Dialog", "TA002"))
        item = self.tableWidget_test_resource.item(13, 3)
        item.setText(_translate("Dialog", "1个，功率>40W"))
        item = self.tableWidget_test_resource.item(14, 0)
        item.setText(_translate("Dialog", "N转换"))
        item = self.tableWidget_test_resource.item(14, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(14, 2)
        item.setText(_translate("Dialog", "TA004/(N/N-K/K)"))
        item = self.tableWidget_test_resource.item(14, 3)
        item.setText(_translate("Dialog", "1个，400W"))
        item = self.tableWidget_test_resource.item(15, 0)
        item.setText(_translate("Dialog", "SMA转换"))
        item = self.tableWidget_test_resource.item(15, 1)
        item.setText(_translate("Dialog", "测试附件"))
        item = self.tableWidget_test_resource.item(15, 2)
        item.setText(_translate("Dialog", "TA005/(SMA-K/K)"))
        item = self.tableWidget_test_resource.item(15, 3)
        item.setText(_translate("Dialog", "1个"))
        self.tableWidget_test_resource.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_test_results_tr_t.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_tr_t.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_tr_t.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_tr_t.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "收发信机单元/发信机"))
        item = self.tableWidget_test_results_tr_r.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_tr_r.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_tr_r.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_tr_r.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "收发信机单元/收信机"))
        item = self.tableWidget_test_results_lna.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_lna.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_lna.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_lna.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "低噪声放大器"))
        item = self.tableWidget_test_results_pa.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_pa.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_pa.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_pa.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "功放模块"))
        item = self.tableWidget_test_results_sc.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_sc.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_sc.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_sc.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "自环器"))
        item = self.tableWidget_test_results_wg.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_wg.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_wg.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_wg.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "波导开关"))
        item = self.tableWidget_test_results_coupler.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_coupler.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_coupler.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_coupler.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "耦合器"))
        item = self.tableWidget_test_results_monitor.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "测试项"))
        item = self.tableWidget_test_results_monitor.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "测试条件"))
        item = self.tableWidget_test_results_monitor.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "测试结果"))
        item = self.tableWidget_test_results_monitor.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试结论"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Dialog", "监控模块"))
import res.iconQrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
