# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\AutoTest\54testframework\ui\ECOM-NS-2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1057, 599)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QDialog{\n"
"background-color:#D0DAE5;\n"
"}\n"
"QTextBrower{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QHeaderView{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei;\n"
"}\n"
"\n"
"QPushButton{         /*按钮自适应拉伸背景*/\n"
"border-width: 2px 15px 2px 15px;\n"
"background-color:#2884D8;\n"
"color: #FFFFFF;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei;\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 1051, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_disassemble = QtWidgets.QWidget()
        self.page_disassemble.setObjectName("page_disassemble")
        self.label_disassemble_imageview = QtWidgets.QLabel(self.page_disassemble)
        self.label_disassemble_imageview.setGeometry(QtCore.QRect(10, 10, 821, 341))
        self.label_disassemble_imageview.setText("")
        self.label_disassemble_imageview.setTextFormat(QtCore.Qt.RichText)
        self.label_disassemble_imageview.setScaledContents(False)
        self.label_disassemble_imageview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disassemble_imageview.setObjectName("label_disassemble_imageview")
        self.pushButton_disassemble_previous = QtWidgets.QPushButton(self.page_disassemble)
        self.pushButton_disassemble_previous.setGeometry(QtCore.QRect(850, 50, 91, 31))
        self.pushButton_disassemble_previous.setObjectName("pushButton_disassemble_previous")
        self.pushButton_disassemble_next = QtWidgets.QPushButton(self.page_disassemble)
        self.pushButton_disassemble_next.setGeometry(QtCore.QRect(850, 90, 91, 31))
        self.pushButton_disassemble_next.setObjectName("pushButton_disassemble_next")
        self.textBrowser_disassemble = QtWidgets.QTextBrowser(self.page_disassemble)
        self.textBrowser_disassemble.setGeometry(QtCore.QRect(10, 370, 821, 161))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.textBrowser_disassemble.setFont(font)
        self.textBrowser_disassemble.setObjectName("textBrowser_disassemble")
        self.stackedWidget.addWidget(self.page_disassemble)
        self.page_testdevice = QtWidgets.QWidget()
        self.page_testdevice.setObjectName("page_testdevice")
        self.label_testdevice_imageview = QtWidgets.QLabel(self.page_testdevice)
        self.label_testdevice_imageview.setGeometry(QtCore.QRect(10, 10, 821, 341))
        self.label_testdevice_imageview.setText("")
        self.label_testdevice_imageview.setScaledContents(False)
        self.label_testdevice_imageview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testdevice_imageview.setObjectName("label_testdevice_imageview")
        self.pushButton_testdevice_previous = QtWidgets.QPushButton(self.page_testdevice)
        self.pushButton_testdevice_previous.setGeometry(QtCore.QRect(850, 50, 91, 31))
        self.pushButton_testdevice_previous.setObjectName("pushButton_testdevice_previous")
        self.pushButton_testdevice_next = QtWidgets.QPushButton(self.page_testdevice)
        self.pushButton_testdevice_next.setGeometry(QtCore.QRect(850, 90, 91, 31))
        self.pushButton_testdevice_next.setObjectName("pushButton_testdevice_next")
        self.textBrowser_testdevice = QtWidgets.QTextBrowser(self.page_testdevice)
        self.textBrowser_testdevice.setGeometry(QtCore.QRect(10, 370, 821, 161))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.textBrowser_testdevice.setFont(font)
        self.textBrowser_testdevice.setObjectName("textBrowser_testdevice")
        self.stackedWidget.addWidget(self.page_testdevice)
        self.page_testexecute = QtWidgets.QWidget()
        self.page_testexecute.setObjectName("page_testexecute")
        self.pushButton_testexecute_next = QtWidgets.QPushButton(self.page_testexecute)
        self.pushButton_testexecute_next.setGeometry(QtCore.QRect(100, 5, 81, 25))
        self.pushButton_testexecute_next.setObjectName("pushButton_testexecute_next")
        self.pushButton_testexecute_last = QtWidgets.QPushButton(self.page_testexecute)
        self.pushButton_testexecute_last.setGeometry(QtCore.QRect(10, 5, 81, 25))
        self.pushButton_testexecute_last.setObjectName("pushButton_testexecute_last")
        self.stackedWidget_testexecute = QtWidgets.QStackedWidget(self.page_testexecute)
        self.stackedWidget_testexecute.setGeometry(QtCore.QRect(10, 50, 1031, 471))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.stackedWidget_testexecute.setFont(font)
        self.stackedWidget_testexecute.setObjectName("stackedWidget_testexecute")
        self.testexecute_page1 = QtWidgets.QWidget()
        self.testexecute_page1.setObjectName("testexecute_page1")
        self.testexecute_page1_label = QtWidgets.QLabel(self.testexecute_page1)
        self.testexecute_page1_label.setGeometry(QtCore.QRect(10, 0, 70, 20))
        self.testexecute_page1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.testexecute_page1_label.setObjectName("testexecute_page1_label")
        self.testexecute_page1_textBrowser = QtWidgets.QTextBrowser(self.testexecute_page1)
        self.testexecute_page1_textBrowser.setGeometry(QtCore.QRect(10, 40, 911, 371))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.testexecute_page1_textBrowser.setFont(font)
        self.testexecute_page1_textBrowser.setObjectName("testexecute_page1_textBrowser")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page1)
        self.testexecute_page2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.testexecute_page2.setFont(font)
        self.testexecute_page2.setObjectName("testexecute_page2")
        self.testexecute_page2_label = QtWidgets.QLabel(self.testexecute_page2)
        self.testexecute_page2_label.setGeometry(QtCore.QRect(10, 0, 84, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.testexecute_page2_label.setFont(font)
        self.testexecute_page2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.testexecute_page2_label.setObjectName("testexecute_page2_label")
        self.testexecute_page2_textBrowser = QtWidgets.QTextBrowser(self.testexecute_page2)
        self.testexecute_page2_textBrowser.setGeometry(QtCore.QRect(10, 40, 911, 371))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.testexecute_page2_textBrowser.setFont(font)
        self.testexecute_page2_textBrowser.setObjectName("testexecute_page2_textBrowser")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page2)
        self.testexecute_page3 = QtWidgets.QWidget()
        self.testexecute_page3.setObjectName("testexecute_page3")
        self.testexecute_page3_textBrowser = QtWidgets.QTextBrowser(self.testexecute_page3)
        self.testexecute_page3_textBrowser.setGeometry(QtCore.QRect(157, 80, 568, 331))
        self.testexecute_page3_textBrowser.setObjectName("testexecute_page3_textBrowser")
        self.testexecute_page3_label_2 = QtWidgets.QLabel(self.testexecute_page3)
        self.testexecute_page3_label_2.setGeometry(QtCore.QRect(10, 0, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.testexecute_page3_label_2.setFont(font)
        self.testexecute_page3_label_2.setObjectName("testexecute_page3_label_2")
        self.splitter_2 = QtWidgets.QSplitter(self.testexecute_page3)
        self.splitter_2.setGeometry(QtCore.QRect(160, 40, 561, 28))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.testexecute_page3_label_3 = QtWidgets.QLabel(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.testexecute_page3_label_3.setFont(font)
        self.testexecute_page3_label_3.setObjectName("testexecute_page3_label_3")
        self.testexecute_page3_lineEdit = QtWidgets.QLineEdit(self.splitter_2)
        self.testexecute_page3_lineEdit.setObjectName("testexecute_page3_lineEdit")
        self.testexecute_page3_pushButton = QtWidgets.QPushButton(self.splitter_2)
        self.testexecute_page3_pushButton.setObjectName("testexecute_page3_pushButton")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page3)
        self.testexecute_page4 = QtWidgets.QWidget()
        self.testexecute_page4.setObjectName("testexecute_page4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.testexecute_page4)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 191, 191))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(9)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.splitter_5 = QtWidgets.QSplitter(self.groupBox_3)
        self.splitter_5.setGeometry(QtCore.QRect(10, 20, 181, 161))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.listWidget_2 = QtWidgets.QListWidget(self.splitter_5)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.testexecute_page4_pushButton_execute = QtWidgets.QPushButton(self.splitter_7)
        self.testexecute_page4_pushButton_execute.setObjectName("testexecute_page4_pushButton_execute")
        self.testexecute_page4_pushButton_last = QtWidgets.QPushButton(self.splitter_7)
        self.testexecute_page4_pushButton_last.setObjectName("testexecute_page4_pushButton_last")
        self.testexecute_page4_pushButton_next = QtWidgets.QPushButton(self.splitter_7)
        self.testexecute_page4_pushButton_next.setObjectName("testexecute_page4_pushButton_next")
        self.layoutWidget = QtWidgets.QWidget(self.testexecute_page4)
        self.layoutWidget.setGeometry(QtCore.QRect(230, 30, 791, 235))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.testexecute_page4_groupBox_ip_port2 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page4_groupBox_ip_port2.setFont(font)
        self.testexecute_page4_groupBox_ip_port2.setObjectName("testexecute_page4_groupBox_ip_port2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.testexecute_page4_groupBox_ip_port2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ip_port2_checkBox_lan15 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan15.setFont(font)
        self.ip_port2_checkBox_lan15.setObjectName("ip_port2_checkBox_lan15")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan15, 1, 6, 1, 1)
        self.ip_port2_checkBox_lan3 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan3.setFont(font)
        self.ip_port2_checkBox_lan3.setObjectName("ip_port2_checkBox_lan3")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan3, 0, 2, 1, 1)
        self.ip_port2_checkBox_lan1 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan1.setFont(font)
        self.ip_port2_checkBox_lan1.setObjectName("ip_port2_checkBox_lan1")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan1, 0, 0, 1, 1)
        self.ip_port2_checkBox_lan5 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan5.setFont(font)
        self.ip_port2_checkBox_lan5.setObjectName("ip_port2_checkBox_lan5")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan5, 0, 4, 1, 1)
        self.ip_port2_checkBox_lan4 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan4.setFont(font)
        self.ip_port2_checkBox_lan4.setObjectName("ip_port2_checkBox_lan4")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan4, 0, 3, 1, 1)
        self.ip_port2_checkBox_lan16 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan16.setFont(font)
        self.ip_port2_checkBox_lan16.setObjectName("ip_port2_checkBox_lan16")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan16, 1, 7, 1, 1)
        self.ip_port2_checkBox_lan10 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan10.setFont(font)
        self.ip_port2_checkBox_lan10.setObjectName("ip_port2_checkBox_lan10")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan10, 1, 1, 1, 1)
        self.ip_port2_checkBox_lan6 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan6.setFont(font)
        self.ip_port2_checkBox_lan6.setObjectName("ip_port2_checkBox_lan6")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan6, 0, 5, 1, 1)
        self.ip_port2_checkBox_lan12 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan12.setFont(font)
        self.ip_port2_checkBox_lan12.setObjectName("ip_port2_checkBox_lan12")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan12, 1, 3, 1, 1)
        self.ip_port2_checkBox_lan14 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan14.setFont(font)
        self.ip_port2_checkBox_lan14.setObjectName("ip_port2_checkBox_lan14")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan14, 1, 5, 1, 1)
        self.ip_port2_checkBox_lan2 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan2.setFont(font)
        self.ip_port2_checkBox_lan2.setObjectName("ip_port2_checkBox_lan2")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan2, 0, 1, 1, 1)
        self.ip_port2_checkBox_lan7 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan7.setFont(font)
        self.ip_port2_checkBox_lan7.setObjectName("ip_port2_checkBox_lan7")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan7, 0, 6, 1, 1)
        self.ip_port2_checkBox_lan8 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan8.setFont(font)
        self.ip_port2_checkBox_lan8.setObjectName("ip_port2_checkBox_lan8")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan8, 0, 7, 1, 1)
        self.ip_port2_checkBox_lan9 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan9.setFont(font)
        self.ip_port2_checkBox_lan9.setObjectName("ip_port2_checkBox_lan9")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan9, 1, 0, 1, 1)
        self.ip_port2_checkBox_lan11 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan11.setFont(font)
        self.ip_port2_checkBox_lan11.setObjectName("ip_port2_checkBox_lan11")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan11, 1, 2, 1, 1)
        self.ip_port2_checkBox_lan13 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port2_checkBox_lan13.setFont(font)
        self.ip_port2_checkBox_lan13.setObjectName("ip_port2_checkBox_lan13")
        self.gridLayout_6.addWidget(self.ip_port2_checkBox_lan13, 1, 4, 1, 1)
        self.gridLayout_5.addWidget(self.testexecute_page4_groupBox_ip_port2, 1, 0, 1, 1)
        self.testexecute_page4_groupBox_ip_port1 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page4_groupBox_ip_port1.setFont(font)
        self.testexecute_page4_groupBox_ip_port1.setObjectName("testexecute_page4_groupBox_ip_port1")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.testexecute_page4_groupBox_ip_port1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ip_port1_checkBox_lan1 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan1.setFont(font)
        self.ip_port1_checkBox_lan1.setObjectName("ip_port1_checkBox_lan1")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan1, 0, 0, 1, 1)
        self.ip_port1_checkBox_lan2 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan2.setFont(font)
        self.ip_port1_checkBox_lan2.setObjectName("ip_port1_checkBox_lan2")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan2, 0, 1, 1, 1)
        self.ip_port1_checkBox_lan3 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan3.setFont(font)
        self.ip_port1_checkBox_lan3.setObjectName("ip_port1_checkBox_lan3")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan3, 0, 2, 1, 1)
        self.ip_port1_checkBox_lan4 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan4.setFont(font)
        self.ip_port1_checkBox_lan4.setObjectName("ip_port1_checkBox_lan4")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan4, 0, 3, 1, 1)
        self.ip_port1_checkBox_lan5 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan5.setFont(font)
        self.ip_port1_checkBox_lan5.setObjectName("ip_port1_checkBox_lan5")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan5, 0, 4, 1, 1)
        self.ip_port1_checkBox_lan6 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan6.setFont(font)
        self.ip_port1_checkBox_lan6.setObjectName("ip_port1_checkBox_lan6")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan6, 0, 5, 1, 1)
        self.ip_port1_checkBox_lan7 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan7.setFont(font)
        self.ip_port1_checkBox_lan7.setObjectName("ip_port1_checkBox_lan7")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan7, 0, 6, 1, 1)
        self.ip_port1_checkBox_lan8 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan8.setFont(font)
        self.ip_port1_checkBox_lan8.setObjectName("ip_port1_checkBox_lan8")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan8, 0, 7, 1, 1)
        self.ip_port1_checkBox_lan9 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan9.setFont(font)
        self.ip_port1_checkBox_lan9.setObjectName("ip_port1_checkBox_lan9")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan9, 1, 0, 1, 1)
        self.ip_port1_checkBox_lan10 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan10.setFont(font)
        self.ip_port1_checkBox_lan10.setObjectName("ip_port1_checkBox_lan10")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan10, 1, 1, 1, 1)
        self.ip_port1_checkBox_lan11 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan11.setFont(font)
        self.ip_port1_checkBox_lan11.setObjectName("ip_port1_checkBox_lan11")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan11, 1, 2, 1, 1)
        self.ip_port1_checkBox_lan12 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan12.setFont(font)
        self.ip_port1_checkBox_lan12.setObjectName("ip_port1_checkBox_lan12")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan12, 1, 3, 1, 1)
        self.ip_port1_checkBox_lan13 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan13.setFont(font)
        self.ip_port1_checkBox_lan13.setObjectName("ip_port1_checkBox_lan13")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan13, 1, 4, 1, 1)
        self.ip_port1_checkBox_lan14 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan14.setFont(font)
        self.ip_port1_checkBox_lan14.setObjectName("ip_port1_checkBox_lan14")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan14, 1, 5, 1, 1)
        self.ip_port1_checkBox_lan15 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan15.setFont(font)
        self.ip_port1_checkBox_lan15.setObjectName("ip_port1_checkBox_lan15")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan15, 1, 6, 1, 1)
        self.ip_port1_checkBox_lan16 = QtWidgets.QCheckBox(self.testexecute_page4_groupBox_ip_port1)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.ip_port1_checkBox_lan16.setFont(font)
        self.ip_port1_checkBox_lan16.setObjectName("ip_port1_checkBox_lan16")
        self.gridLayout_7.addWidget(self.ip_port1_checkBox_lan16, 1, 7, 1, 1)
        self.gridLayout_5.addWidget(self.testexecute_page4_groupBox_ip_port1, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.testexecute_page4)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 270, 1001, 221))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.testexecute_page4_textBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.testexecute_page4_textBrowser.setGeometry(QtCore.QRect(10, 30, 901, 171))
        self.testexecute_page4_textBrowser.setObjectName("testexecute_page4_textBrowser")
        self.testexecute_page4_label = QtWidgets.QLabel(self.testexecute_page4)
        self.testexecute_page4_label.setGeometry(QtCore.QRect(30, 0, 153, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.testexecute_page4_label.setFont(font)
        self.testexecute_page4_label.setObjectName("testexecute_page4_label")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page4)
        self.testexecute_page3_label = QtWidgets.QLabel(self.page_testexecute)
        self.testexecute_page3_label.setGeometry(QtCore.QRect(350, 30, 153, 17))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.testexecute_page3_label.setFont(font)
        self.testexecute_page3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.testexecute_page3_label.setObjectName("testexecute_page3_label")
        self.stackedWidget.addWidget(self.page_testexecute)
        self.pageTestData = QtWidgets.QWidget()
        self.pageTestData.setObjectName("pageTestData")
        self.pushButton_TestData_export = QtWidgets.QPushButton(self.pageTestData)
        self.pushButton_TestData_export.setGeometry(QtCore.QRect(860, 100, 111, 31))
        self.pushButton_TestData_export.setObjectName("pushButton_TestData_export")
        self.pushButton_TestData_upload = QtWidgets.QPushButton(self.pageTestData)
        self.pushButton_TestData_upload.setGeometry(QtCore.QRect(860, 150, 111, 31))
        self.pushButton_TestData_upload.setObjectName("pushButton_TestData_upload")
        self.test_data_tableWidget = QtWidgets.QTableWidget(self.pageTestData)
        self.test_data_tableWidget.setGeometry(QtCore.QRect(20, 80, 831, 411))
        self.test_data_tableWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.test_data_tableWidget.setObjectName("test_data_tableWidget")
        self.test_data_tableWidget.setColumnCount(7)
        self.test_data_tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 5, item)
        self.label_4 = QtWidgets.QLabel(self.pageTestData)
        self.label_4.setGeometry(QtCore.QRect(390, 20, 84, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.pageTestData)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.label_sytem_test_procedure_label = QtWidgets.QLabel(Dialog)
        self.label_sytem_test_procedure_label.setGeometry(QtCore.QRect(70, 0, 191, 31))
        self.label_sytem_test_procedure_label.setObjectName("label_sytem_test_procedure_label")
        self.label_label_sytem_test_procedure = QtWidgets.QLabel(Dialog)
        self.label_label_sytem_test_procedure.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.label_label_sytem_test_procedure.setObjectName("label_label_sytem_test_procedure")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_4 = QtWidgets.QSplitter(Dialog)
        self.splitter_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setGeometry(QtCore.QRect(840, 1, 132, 39))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_last = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_last.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.pushButton_last.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon/last4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last.setIcon(icon)
        self.pushButton_last.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_last.setObjectName("pushButton_last")
        self.pushButton_next = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_next.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon/next4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon1)
        self.pushButton_next.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_close = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_close.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon/close4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon2)
        self.pushButton_close.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Dialog)
        self.stackedWidget_testexecute.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_disassemble_previous.setText(_translate("Dialog", "上一步"))
        self.pushButton_disassemble_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testdevice_previous.setText(_translate("Dialog", "上一步"))
        self.pushButton_testdevice_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testexecute_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testexecute_last.setText(_translate("Dialog", "上一步"))
        self.testexecute_page1_label.setText(_translate("Dialog", "保险丝测试"))
        self.testexecute_page2_label.setText(_translate("Dialog", "电源部分测试"))
        self.testexecute_page3_label_2.setText(_translate("Dialog", "Ping测试"))
        self.testexecute_page3_label_3.setText(_translate("Dialog", "IP地址"))
        self.testexecute_page3_pushButton.setText(_translate("Dialog", "ping"))
        self.groupBox_3.setTitle(_translate("Dialog", "交换机类型"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("Dialog", "其他交换机"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.testexecute_page4_pushButton_execute.setText(_translate("Dialog", "执行测试"))
        self.testexecute_page4_pushButton_last.setText(_translate("Dialog", "上一步"))
        self.testexecute_page4_pushButton_next.setText(_translate("Dialog", "下一步"))
        self.testexecute_page4_groupBox_ip_port2.setTitle(_translate("Dialog", "IP误码仪测试端口2"))
        self.ip_port2_checkBox_lan15.setText(_translate("Dialog", "LAN15"))
        self.ip_port2_checkBox_lan3.setText(_translate("Dialog", "LAN3"))
        self.ip_port2_checkBox_lan1.setText(_translate("Dialog", "LAN1"))
        self.ip_port2_checkBox_lan5.setText(_translate("Dialog", "LAN5"))
        self.ip_port2_checkBox_lan4.setText(_translate("Dialog", "LAN4"))
        self.ip_port2_checkBox_lan16.setText(_translate("Dialog", "LAN16"))
        self.ip_port2_checkBox_lan10.setText(_translate("Dialog", "LAN10"))
        self.ip_port2_checkBox_lan6.setText(_translate("Dialog", "LAN6"))
        self.ip_port2_checkBox_lan12.setText(_translate("Dialog", "LAN12"))
        self.ip_port2_checkBox_lan14.setText(_translate("Dialog", "LAN14"))
        self.ip_port2_checkBox_lan2.setText(_translate("Dialog", "LAN2"))
        self.ip_port2_checkBox_lan7.setText(_translate("Dialog", "LAN7"))
        self.ip_port2_checkBox_lan8.setText(_translate("Dialog", "LAN8"))
        self.ip_port2_checkBox_lan9.setText(_translate("Dialog", "LAN9"))
        self.ip_port2_checkBox_lan11.setText(_translate("Dialog", "LAN11"))
        self.ip_port2_checkBox_lan13.setText(_translate("Dialog", "LAN13"))
        self.testexecute_page4_groupBox_ip_port1.setTitle(_translate("Dialog", "IP误码仪测试端口1"))
        self.ip_port1_checkBox_lan1.setText(_translate("Dialog", "LAN1"))
        self.ip_port1_checkBox_lan2.setText(_translate("Dialog", "LAN2"))
        self.ip_port1_checkBox_lan3.setText(_translate("Dialog", "LAN3"))
        self.ip_port1_checkBox_lan4.setText(_translate("Dialog", "LAN4"))
        self.ip_port1_checkBox_lan5.setText(_translate("Dialog", "LAN5"))
        self.ip_port1_checkBox_lan6.setText(_translate("Dialog", "LAN6"))
        self.ip_port1_checkBox_lan7.setText(_translate("Dialog", "LAN7"))
        self.ip_port1_checkBox_lan8.setText(_translate("Dialog", "LAN8"))
        self.ip_port1_checkBox_lan9.setText(_translate("Dialog", "LAN9"))
        self.ip_port1_checkBox_lan10.setText(_translate("Dialog", "LAN10"))
        self.ip_port1_checkBox_lan11.setText(_translate("Dialog", "LAN11"))
        self.ip_port1_checkBox_lan12.setText(_translate("Dialog", "LAN12"))
        self.ip_port1_checkBox_lan13.setText(_translate("Dialog", "LAN13"))
        self.ip_port1_checkBox_lan14.setText(_translate("Dialog", "LAN14"))
        self.ip_port1_checkBox_lan15.setText(_translate("Dialog", "LAN15"))
        self.ip_port1_checkBox_lan16.setText(_translate("Dialog", "LAN16"))
        self.groupBox_4.setTitle(_translate("Dialog", "测试说明"))
        self.testexecute_page4_label.setText(_translate("Dialog", "IP误码仪测试以太网接口"))
        self.testexecute_page3_label.setText(_translate("Dialog", "交换主控板测试"))
        self.pushButton_TestData_export.setText(_translate("Dialog", "数据导出"))
        self.pushButton_TestData_upload.setText(_translate("Dialog", "数据上传"))
        item = self.test_data_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.test_data_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.test_data_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.test_data_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.test_data_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.test_data_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "交换机型号"))
        item = self.test_data_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Com1"))
        item = self.test_data_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Com2"))
        item = self.test_data_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试指标"))
        item = self.test_data_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "丢包数"))
        item = self.test_data_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "测试结果"))
        __sortingEnabled = self.test_data_tableWidget.isSortingEnabled()
        self.test_data_tableWidget.setSortingEnabled(False)
        item = self.test_data_tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "LAN1"))
        item = self.test_data_tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "LAN2"))
        item = self.test_data_tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(0, 4)
        item.setText(_translate("Dialog", "10"))
        item = self.test_data_tableWidget.item(0, 5)
        item.setText(_translate("Dialog", "通过"))
        item = self.test_data_tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "LAN3"))
        item = self.test_data_tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "LAN4"))
        item = self.test_data_tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(1, 4)
        item.setText(_translate("Dialog", "103"))
        item = self.test_data_tableWidget.item(1, 5)
        item.setText(_translate("Dialog", "不通过"))
        item = self.test_data_tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "LAN6"))
        item = self.test_data_tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "LAN7"))
        item = self.test_data_tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(2, 4)
        item.setText(_translate("Dialog", "56"))
        item = self.test_data_tableWidget.item(2, 5)
        item.setText(_translate("Dialog", "通过"))
        item = self.test_data_tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "LAN8"))
        item = self.test_data_tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "LAN9"))
        item = self.test_data_tableWidget.item(3, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(3, 4)
        item.setText(_translate("Dialog", "23"))
        item = self.test_data_tableWidget.item(3, 5)
        item.setText(_translate("Dialog", "通过"))
        item = self.test_data_tableWidget.item(4, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(4, 1)
        item.setText(_translate("Dialog", "LAN10"))
        item = self.test_data_tableWidget.item(4, 2)
        item.setText(_translate("Dialog", "LAN11"))
        item = self.test_data_tableWidget.item(4, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(4, 4)
        item.setText(_translate("Dialog", "76"))
        item = self.test_data_tableWidget.item(4, 5)
        item.setText(_translate("Dialog", "通过"))
        self.test_data_tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("Dialog", "测试数据管理"))
        self.label_sytem_test_procedure_label.setText(_translate("Dialog", "系统拆机演示"))
        self.label_label_sytem_test_procedure.setText(_translate("Dialog", "测试流程："))

import iconQrc_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

