# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\sourcecode\54\Eric6WorkSpace\COM_CONTROL_DEVICE.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1032, 599)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QDialog{\n"
"background-color:#D0DAE5;\n"
"}\n"
"QTextBrower{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QHeaderView{\n"
"background-color:#D0DAE5;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei;\n"
"}\n"
"\n"
"QPushButton{         /*按钮自适应拉伸背景*/\n"
"border-width: 2px 15px 2px 15px;\n"
"background-color:#2884D8;\n"
"color: #FFFFFF;\n"
"font-size:14px;\n"
"font-family:Microsoft YaHei;\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 1031, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_disassemble = QtWidgets.QWidget()
        self.page_disassemble.setObjectName("page_disassemble")
        self.label_disassemble_imageview = QtWidgets.QLabel(self.page_disassemble)
        self.label_disassemble_imageview.setGeometry(QtCore.QRect(10, 10, 821, 341))
        self.label_disassemble_imageview.setText("")
        self.label_disassemble_imageview.setTextFormat(QtCore.Qt.RichText)
        self.label_disassemble_imageview.setScaledContents(True)
        self.label_disassemble_imageview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disassemble_imageview.setObjectName("label_disassemble_imageview")
        self.pushButton_disassemble_previous = QtWidgets.QPushButton(self.page_disassemble)
        self.pushButton_disassemble_previous.setGeometry(QtCore.QRect(850, 50, 91, 31))
        self.pushButton_disassemble_previous.setObjectName("pushButton_disassemble_previous")
        self.pushButton_disassemble_next = QtWidgets.QPushButton(self.page_disassemble)
        self.pushButton_disassemble_next.setGeometry(QtCore.QRect(850, 90, 91, 31))
        self.pushButton_disassemble_next.setObjectName("pushButton_disassemble_next")
        self.textBrowser_disassemble = QtWidgets.QTextBrowser(self.page_disassemble)
        self.textBrowser_disassemble.setGeometry(QtCore.QRect(10, 370, 821, 161))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.textBrowser_disassemble.setFont(font)
        self.textBrowser_disassemble.setObjectName("textBrowser_disassemble")
        self.stackedWidget.addWidget(self.page_disassemble)
        self.page_testdevice = QtWidgets.QWidget()
        self.page_testdevice.setObjectName("page_testdevice")
        self.label_testdevice_imageview = QtWidgets.QLabel(self.page_testdevice)
        self.label_testdevice_imageview.setGeometry(QtCore.QRect(10, 10, 821, 341))
        self.label_testdevice_imageview.setText("")
        self.label_testdevice_imageview.setScaledContents(False)
        self.label_testdevice_imageview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testdevice_imageview.setObjectName("label_testdevice_imageview")
        self.pushButton_testdevice_previous = QtWidgets.QPushButton(self.page_testdevice)
        self.pushButton_testdevice_previous.setGeometry(QtCore.QRect(850, 50, 91, 31))
        self.pushButton_testdevice_previous.setObjectName("pushButton_testdevice_previous")
        self.pushButton_testdevice_next = QtWidgets.QPushButton(self.page_testdevice)
        self.pushButton_testdevice_next.setGeometry(QtCore.QRect(850, 90, 91, 31))
        self.pushButton_testdevice_next.setObjectName("pushButton_testdevice_next")
        self.textBrowser_testdevice = QtWidgets.QTextBrowser(self.page_testdevice)
        self.textBrowser_testdevice.setGeometry(QtCore.QRect(10, 370, 821, 161))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.textBrowser_testdevice.setFont(font)
        self.textBrowser_testdevice.setObjectName("textBrowser_testdevice")
        self.stackedWidget.addWidget(self.page_testdevice)
        self.page_testexecute = QtWidgets.QWidget()
        self.page_testexecute.setObjectName("page_testexecute")
        self.pushButton_testexecute_next = QtWidgets.QPushButton(self.page_testexecute)
        self.pushButton_testexecute_next.setGeometry(QtCore.QRect(100, 5, 81, 25))
        self.pushButton_testexecute_next.setObjectName("pushButton_testexecute_next")
        self.pushButton_testexecute_last = QtWidgets.QPushButton(self.page_testexecute)
        self.pushButton_testexecute_last.setGeometry(QtCore.QRect(10, 5, 81, 25))
        self.pushButton_testexecute_last.setObjectName("pushButton_testexecute_last")
        self.stackedWidget_testexecute = QtWidgets.QStackedWidget(self.page_testexecute)
        self.stackedWidget_testexecute.setGeometry(QtCore.QRect(10, 50, 1011, 481))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.stackedWidget_testexecute.setFont(font)
        self.stackedWidget_testexecute.setObjectName("stackedWidget_testexecute")
        self.testexecute_page1 = QtWidgets.QWidget()
        self.testexecute_page1.setObjectName("testexecute_page1")
        self.testexecute_page1_label = QtWidgets.QLabel(self.testexecute_page1)
        self.testexecute_page1_label.setGeometry(QtCore.QRect(10, 0, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page1_label.setFont(font)
        self.testexecute_page1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.testexecute_page1_label.setObjectName("testexecute_page1_label")
        self.testexecute_page1_textBrowser = QtWidgets.QTextBrowser(self.testexecute_page1)
        self.testexecute_page1_textBrowser.setGeometry(QtCore.QRect(10, 40, 911, 371))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page1_textBrowser.setFont(font)
        self.testexecute_page1_textBrowser.setObjectName("testexecute_page1_textBrowser")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page1)
        self.testexecute_page2 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page2.setFont(font)
        self.testexecute_page2.setObjectName("testexecute_page2")
        self.testexecute_page2_label = QtWidgets.QLabel(self.testexecute_page2)
        self.testexecute_page2_label.setGeometry(QtCore.QRect(10, 0, 84, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page2_label.setFont(font)
        self.testexecute_page2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.testexecute_page2_label.setObjectName("testexecute_page2_label")
        self.testexecute_page2_textBrowser = QtWidgets.QTextBrowser(self.testexecute_page2)
        self.testexecute_page2_textBrowser.setGeometry(QtCore.QRect(10, 40, 911, 371))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page2_textBrowser.setFont(font)
        self.testexecute_page2_textBrowser.setObjectName("testexecute_page2_textBrowser")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page2)
        self.testexecute_page3 = QtWidgets.QWidget()
        self.testexecute_page3.setObjectName("testexecute_page3")
        self.testexecute_page3_label_2 = QtWidgets.QLabel(self.testexecute_page3)
        self.testexecute_page3_label_2.setGeometry(QtCore.QRect(10, 0, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page3_label_2.setFont(font)
        self.testexecute_page3_label_2.setObjectName("testexecute_page3_label_2")
        self.testexecute_page3_label_3 = QtWidgets.QLabel(self.testexecute_page3)
        self.testexecute_page3_label_3.setGeometry(QtCore.QRect(10, 50, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page3_label_3.setFont(font)
        self.testexecute_page3_label_3.setObjectName("testexecute_page3_label_3")
        self.widget = QtWidgets.QWidget(self.testexecute_page3)
        self.widget.setGeometry(QtCore.QRect(10, 80, 681, 33))
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.testexecute_page3_checkBox_lan2 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan2.setFont(font)
        self.testexecute_page3_checkBox_lan2.setObjectName("testexecute_page3_checkBox_lan2")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan2, 0, 0, 1, 1)
        self.testexecute_page3_checkBox_lan3 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan3.setFont(font)
        self.testexecute_page3_checkBox_lan3.setObjectName("testexecute_page3_checkBox_lan3")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan3, 0, 1, 1, 1)
        self.testexecute_page3_checkBox_lan4 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan4.setFont(font)
        self.testexecute_page3_checkBox_lan4.setObjectName("testexecute_page3_checkBox_lan4")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan4, 0, 2, 1, 1)
        self.testexecute_page3_checkBox_lan5 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan5.setFont(font)
        self.testexecute_page3_checkBox_lan5.setObjectName("testexecute_page3_checkBox_lan5")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan5, 0, 3, 1, 1)
        self.testexecute_page3_checkBox_lan6 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan6.setFont(font)
        self.testexecute_page3_checkBox_lan6.setObjectName("testexecute_page3_checkBox_lan6")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan6, 0, 4, 1, 1)
        self.testexecute_page3_checkBox_lan7 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan7.setFont(font)
        self.testexecute_page3_checkBox_lan7.setObjectName("testexecute_page3_checkBox_lan7")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan7, 0, 5, 1, 1)
        self.testexecute_page3_checkBox_lan8 = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page3_checkBox_lan8.setFont(font)
        self.testexecute_page3_checkBox_lan8.setObjectName("testexecute_page3_checkBox_lan8")
        self.gridLayout_8.addWidget(self.testexecute_page3_checkBox_lan8, 0, 6, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.testexecute_page3)
        self.widget1.setGeometry(QtCore.QRect(0, 222, 1001, 251))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.widget1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.testexecute_page3_textBrowser_guide = QtWidgets.QTextBrowser(self.groupBox)
        self.testexecute_page3_textBrowser_guide.setObjectName("testexecute_page3_textBrowser_guide")
        self.gridLayout_2.addWidget(self.testexecute_page3_textBrowser_guide, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.testexecute_page3_textBrowser_log = QtWidgets.QTextBrowser(self.groupBox_2)
        self.testexecute_page3_textBrowser_log.setObjectName("testexecute_page3_textBrowser_log")
        self.gridLayout_3.addWidget(self.testexecute_page3_textBrowser_log, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.testexecute_page3)
        self.widget2.setGeometry(QtCore.QRect(790, 140, 195, 41))
        self.widget2.setObjectName("widget2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.testexecute_page3_pushButton_execute = QtWidgets.QPushButton(self.widget2)
        self.testexecute_page3_pushButton_execute.setObjectName("testexecute_page3_pushButton_execute")
        self.gridLayout_9.addWidget(self.testexecute_page3_pushButton_execute, 0, 0, 1, 1)
        self.testexecute_page3_pushButton_savedata = QtWidgets.QPushButton(self.widget2)
        self.testexecute_page3_pushButton_savedata.setObjectName("testexecute_page3_pushButton_savedata")
        self.gridLayout_9.addWidget(self.testexecute_page3_pushButton_savedata, 0, 1, 1, 1)
        self.stackedWidget_testexecute.addWidget(self.testexecute_page3)
        self.testexecute_page4 = QtWidgets.QWidget()
        self.testexecute_page4.setObjectName("testexecute_page4")
        self.testexecute_page4_label_4 = QtWidgets.QLabel(self.testexecute_page4)
        self.testexecute_page4_label_4.setGeometry(QtCore.QRect(20, 0, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_4.setFont(font)
        self.testexecute_page4_label_4.setObjectName("testexecute_page4_label_4")
        self.layoutWidget = QtWidgets.QWidget(self.testexecute_page4)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 230, 1001, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.testexecute_page4_textBrowser_guide = QtWidgets.QTextBrowser(self.groupBox_3)
        self.testexecute_page4_textBrowser_guide.setObjectName("testexecute_page4_textBrowser_guide")
        self.gridLayout_6.addWidget(self.testexecute_page4_textBrowser_guide, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.testexecute_page4_textBrowser_log = QtWidgets.QTextBrowser(self.groupBox_4)
        self.testexecute_page4_textBrowser_log.setObjectName("testexecute_page4_textBrowser_log")
        self.gridLayout_7.addWidget(self.testexecute_page4_textBrowser_log, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.testexecute_page4_label_5 = QtWidgets.QLabel(self.testexecute_page4)
        self.testexecute_page4_label_5.setGeometry(QtCore.QRect(30, 30, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_5.setFont(font)
        self.testexecute_page4_label_5.setObjectName("testexecute_page4_label_5")
        self.testexecute_page4_label_10 = QtWidgets.QLabel(self.testexecute_page4)
        self.testexecute_page4_label_10.setGeometry(QtCore.QRect(30, 90, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_10.setFont(font)
        self.testexecute_page4_label_10.setObjectName("testexecute_page4_label_10")
        self.layoutWidget_2 = QtWidgets.QWidget(self.testexecute_page4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 150, 503, 35))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.testexecute_page4_label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_8.setFont(font)
        self.testexecute_page4_label_8.setObjectName("testexecute_page4_label_8")
        self.gridLayout_12.addWidget(self.testexecute_page4_label_8, 0, 0, 1, 1)
        self.testexecute_page4_lineEdit_remote_ip = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page4_lineEdit_remote_ip.setFont(font)
        self.testexecute_page4_lineEdit_remote_ip.setObjectName("testexecute_page4_lineEdit_remote_ip")
        self.gridLayout_12.addWidget(self.testexecute_page4_lineEdit_remote_ip, 0, 1, 1, 1)
        self.testexecute_page4_label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_9.setFont(font)
        self.testexecute_page4_label_9.setObjectName("testexecute_page4_label_9")
        self.gridLayout_12.addWidget(self.testexecute_page4_label_9, 0, 2, 1, 1)
        self.testexecute_page4_lineEdit_remote_port = QtWidgets.QLineEdit(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page4_lineEdit_remote_port.setFont(font)
        self.testexecute_page4_lineEdit_remote_port.setObjectName("testexecute_page4_lineEdit_remote_port")
        self.gridLayout_12.addWidget(self.testexecute_page4_lineEdit_remote_port, 0, 3, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.testexecute_page4)
        self.layoutWidget_3.setGeometry(QtCore.QRect(790, 150, 195, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.testexecute_page4_pushButton_execute = QtWidgets.QPushButton(self.layoutWidget_3)
        self.testexecute_page4_pushButton_execute.setObjectName("testexecute_page4_pushButton_execute")
        self.gridLayout_13.addWidget(self.testexecute_page4_pushButton_execute, 0, 0, 1, 1)
        self.testexecute_page4_pushButton_savedata = QtWidgets.QPushButton(self.layoutWidget_3)
        self.testexecute_page4_pushButton_savedata.setObjectName("testexecute_page4_pushButton_savedata")
        self.gridLayout_13.addWidget(self.testexecute_page4_pushButton_savedata, 0, 1, 1, 1)
        self.testexecute_page4_pushButton_local_disconnect = QtWidgets.QPushButton(self.testexecute_page4)
        self.testexecute_page4_pushButton_local_disconnect.setGeometry(QtCore.QRect(530, 110, 93, 29))
        self.testexecute_page4_pushButton_local_disconnect.setObjectName("testexecute_page4_pushButton_local_disconnect")
        self.testexecute_page4_pushButton_remote_link = QtWidgets.QPushButton(self.testexecute_page4)
        self.testexecute_page4_pushButton_remote_link.setGeometry(QtCore.QRect(530, 150, 93, 29))
        self.testexecute_page4_pushButton_remote_link.setObjectName("testexecute_page4_pushButton_remote_link")
        self.widget3 = QtWidgets.QWidget(self.testexecute_page4)
        self.widget3.setGeometry(QtCore.QRect(30, 50, 375, 33))
        self.widget3.setObjectName("widget3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.testexecute_page4_checkBox_com1 = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page4_checkBox_com1.setFont(font)
        self.testexecute_page4_checkBox_com1.setObjectName("testexecute_page4_checkBox_com1")
        self.gridLayout_10.addWidget(self.testexecute_page4_checkBox_com1, 0, 0, 1, 1)
        self.testexecute_page4_checkBox_com2 = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page4_checkBox_com2.setFont(font)
        self.testexecute_page4_checkBox_com2.setObjectName("testexecute_page4_checkBox_com2")
        self.gridLayout_10.addWidget(self.testexecute_page4_checkBox_com2, 0, 1, 1, 1)
        self.testexecute_page4_checkBox_com3 = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page4_checkBox_com3.setFont(font)
        self.testexecute_page4_checkBox_com3.setObjectName("testexecute_page4_checkBox_com3")
        self.gridLayout_10.addWidget(self.testexecute_page4_checkBox_com3, 0, 2, 1, 1)
        self.testexecute_page4_checkBox_com4 = QtWidgets.QCheckBox(self.widget3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page4_checkBox_com4.setFont(font)
        self.testexecute_page4_checkBox_com4.setObjectName("testexecute_page4_checkBox_com4")
        self.gridLayout_10.addWidget(self.testexecute_page4_checkBox_com4, 0, 3, 1, 1)
        self.widget4 = QtWidgets.QWidget(self.testexecute_page4)
        self.widget4.setGeometry(QtCore.QRect(20, 110, 503, 35))
        self.widget4.setObjectName("widget4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.testexecute_page4_label_6 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_6.setFont(font)
        self.testexecute_page4_label_6.setObjectName("testexecute_page4_label_6")
        self.gridLayout_11.addWidget(self.testexecute_page4_label_6, 0, 0, 1, 1)
        self.testexecute_page4_lineEdit_local_ip = QtWidgets.QLineEdit(self.widget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page4_lineEdit_local_ip.setFont(font)
        self.testexecute_page4_lineEdit_local_ip.setObjectName("testexecute_page4_lineEdit_local_ip")
        self.gridLayout_11.addWidget(self.testexecute_page4_lineEdit_local_ip, 0, 1, 1, 1)
        self.testexecute_page4_label_7 = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page4_label_7.setFont(font)
        self.testexecute_page4_label_7.setObjectName("testexecute_page4_label_7")
        self.gridLayout_11.addWidget(self.testexecute_page4_label_7, 0, 2, 1, 1)
        self.testexecute_page4_lineEdit_local_port = QtWidgets.QLineEdit(self.widget4)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page4_lineEdit_local_port.setFont(font)
        self.testexecute_page4_lineEdit_local_port.setObjectName("testexecute_page4_lineEdit_local_port")
        self.gridLayout_11.addWidget(self.testexecute_page4_lineEdit_local_port, 0, 3, 1, 1)
        self.stackedWidget_testexecute.addWidget(self.testexecute_page4)
        self.testexecute_page5 = QtWidgets.QWidget()
        self.testexecute_page5.setObjectName("testexecute_page5")
        self.layoutWidget_4 = QtWidgets.QWidget(self.testexecute_page5)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 230, 1001, 251))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget_4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.testexecute_page5_textBrowser_guide = QtWidgets.QTextBrowser(self.groupBox_5)
        self.testexecute_page5_textBrowser_guide.setObjectName("testexecute_page5_textBrowser_guide")
        self.gridLayout_15.addWidget(self.testexecute_page5_textBrowser_guide, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget_4)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.testexecute_page5_textBrowser_log = QtWidgets.QTextBrowser(self.groupBox_6)
        self.testexecute_page5_textBrowser_log.setObjectName("testexecute_page5_textBrowser_log")
        self.gridLayout_16.addWidget(self.testexecute_page5_textBrowser_log, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.testexecute_page5_label_11 = QtWidgets.QLabel(self.testexecute_page5)
        self.testexecute_page5_label_11.setGeometry(QtCore.QRect(30, 90, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_11.setFont(font)
        self.testexecute_page5_label_11.setObjectName("testexecute_page5_label_11")
        self.layoutWidget_5 = QtWidgets.QWidget(self.testexecute_page5)
        self.layoutWidget_5.setGeometry(QtCore.QRect(30, 50, 375, 33))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.testexecute_page5_checkBox_com5 = QtWidgets.QCheckBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page5_checkBox_com5.setFont(font)
        self.testexecute_page5_checkBox_com5.setObjectName("testexecute_page5_checkBox_com5")
        self.gridLayout_17.addWidget(self.testexecute_page5_checkBox_com5, 0, 0, 1, 1)
        self.testexecute_page5_checkBox_com6 = QtWidgets.QCheckBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page5_checkBox_com6.setFont(font)
        self.testexecute_page5_checkBox_com6.setObjectName("testexecute_page5_checkBox_com6")
        self.gridLayout_17.addWidget(self.testexecute_page5_checkBox_com6, 0, 1, 1, 1)
        self.testexecute_page5_checkBox_com7 = QtWidgets.QCheckBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page5_checkBox_com7.setFont(font)
        self.testexecute_page5_checkBox_com7.setObjectName("testexecute_page5_checkBox_com7")
        self.gridLayout_17.addWidget(self.testexecute_page5_checkBox_com7, 0, 2, 1, 1)
        self.testexecute_page5_checkBox_com8 = QtWidgets.QCheckBox(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page5_checkBox_com8.setFont(font)
        self.testexecute_page5_checkBox_com8.setObjectName("testexecute_page5_checkBox_com8")
        self.gridLayout_17.addWidget(self.testexecute_page5_checkBox_com8, 0, 3, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.testexecute_page5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(30, 110, 503, 35))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.testexecute_page5_label_12 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_12.setFont(font)
        self.testexecute_page5_label_12.setObjectName("testexecute_page5_label_12")
        self.gridLayout_18.addWidget(self.testexecute_page5_label_12, 0, 0, 1, 1)
        self.testexecute_page5_lineEdit_local_ip = QtWidgets.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page5_lineEdit_local_ip.setFont(font)
        self.testexecute_page5_lineEdit_local_ip.setObjectName("testexecute_page5_lineEdit_local_ip")
        self.gridLayout_18.addWidget(self.testexecute_page5_lineEdit_local_ip, 0, 1, 1, 1)
        self.testexecute_page5_label_13 = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_13.setFont(font)
        self.testexecute_page5_label_13.setObjectName("testexecute_page5_label_13")
        self.gridLayout_18.addWidget(self.testexecute_page5_label_13, 0, 2, 1, 1)
        self.testexecute_page5_lineEdit_local_port = QtWidgets.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page5_lineEdit_local_port.setFont(font)
        self.testexecute_page5_lineEdit_local_port.setObjectName("testexecute_page5_lineEdit_local_port")
        self.gridLayout_18.addWidget(self.testexecute_page5_lineEdit_local_port, 0, 3, 1, 1)
        self.testexecute_page5_label_14 = QtWidgets.QLabel(self.testexecute_page5)
        self.testexecute_page5_label_14.setGeometry(QtCore.QRect(20, 0, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_14.setFont(font)
        self.testexecute_page5_label_14.setObjectName("testexecute_page5_label_14")
        self.layoutWidget_7 = QtWidgets.QWidget(self.testexecute_page5)
        self.layoutWidget_7.setGeometry(QtCore.QRect(800, 150, 195, 41))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.layoutWidget_7)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.testexecute_page5_pushButton_execute = QtWidgets.QPushButton(self.layoutWidget_7)
        self.testexecute_page5_pushButton_execute.setObjectName("testexecute_page5_pushButton_execute")
        self.gridLayout_19.addWidget(self.testexecute_page5_pushButton_execute, 0, 0, 1, 1)
        self.testexecute_page5_pushButton_savedata = QtWidgets.QPushButton(self.layoutWidget_7)
        self.testexecute_page5_pushButton_savedata.setObjectName("testexecute_page5_pushButton_savedata")
        self.gridLayout_19.addWidget(self.testexecute_page5_pushButton_savedata, 0, 1, 1, 1)
        self.testexecute_page5_pushButton_local_disconnect = QtWidgets.QPushButton(self.testexecute_page5)
        self.testexecute_page5_pushButton_local_disconnect.setGeometry(QtCore.QRect(540, 110, 93, 29))
        self.testexecute_page5_pushButton_local_disconnect.setObjectName("testexecute_page5_pushButton_local_disconnect")
        self.layoutWidget_8 = QtWidgets.QWidget(self.testexecute_page5)
        self.layoutWidget_8.setGeometry(QtCore.QRect(30, 150, 503, 35))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.layoutWidget_8)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.testexecute_page5_label_15 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_15.setFont(font)
        self.testexecute_page5_label_15.setObjectName("testexecute_page5_label_15")
        self.gridLayout_20.addWidget(self.testexecute_page5_label_15, 0, 0, 1, 1)
        self.testexecute_page5_lineEdit_remote_ip = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page5_lineEdit_remote_ip.setFont(font)
        self.testexecute_page5_lineEdit_remote_ip.setObjectName("testexecute_page5_lineEdit_remote_ip")
        self.gridLayout_20.addWidget(self.testexecute_page5_lineEdit_remote_ip, 0, 1, 1, 1)
        self.testexecute_page5_label_16 = QtWidgets.QLabel(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_16.setFont(font)
        self.testexecute_page5_label_16.setObjectName("testexecute_page5_label_16")
        self.gridLayout_20.addWidget(self.testexecute_page5_label_16, 0, 2, 1, 1)
        self.testexecute_page5_lineEdit_remote_port = QtWidgets.QLineEdit(self.layoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page5_lineEdit_remote_port.setFont(font)
        self.testexecute_page5_lineEdit_remote_port.setObjectName("testexecute_page5_lineEdit_remote_port")
        self.gridLayout_20.addWidget(self.testexecute_page5_lineEdit_remote_port, 0, 3, 1, 1)
        self.testexecute_page5_label_17 = QtWidgets.QLabel(self.testexecute_page5)
        self.testexecute_page5_label_17.setGeometry(QtCore.QRect(30, 30, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page5_label_17.setFont(font)
        self.testexecute_page5_label_17.setObjectName("testexecute_page5_label_17")
        self.testexecute_page5_pushButton_remote_link = QtWidgets.QPushButton(self.testexecute_page5)
        self.testexecute_page5_pushButton_remote_link.setGeometry(QtCore.QRect(540, 150, 93, 29))
        self.testexecute_page5_pushButton_remote_link.setObjectName("testexecute_page5_pushButton_remote_link")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page5)
        self.testexecute_page6 = QtWidgets.QWidget()
        self.testexecute_page6.setObjectName("testexecute_page6")
        self.layoutWidget_9 = QtWidgets.QWidget(self.testexecute_page6)
        self.layoutWidget_9.setGeometry(QtCore.QRect(10, 230, 1001, 251))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget_9)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.groupBox_7 = QtWidgets.QGroupBox(self.layoutWidget_9)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.testexecute_page6_textBrowser_guide = QtWidgets.QTextBrowser(self.groupBox_7)
        self.testexecute_page6_textBrowser_guide.setObjectName("testexecute_page6_textBrowser_guide")
        self.gridLayout_22.addWidget(self.testexecute_page6_textBrowser_guide, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.layoutWidget_9)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.testexecute_page6_textBrowser_log = QtWidgets.QTextBrowser(self.groupBox_8)
        self.testexecute_page6_textBrowser_log.setObjectName("testexecute_page6_textBrowser_log")
        self.gridLayout_23.addWidget(self.testexecute_page6_textBrowser_log, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.testexecute_page6_label_18 = QtWidgets.QLabel(self.testexecute_page6)
        self.testexecute_page6_label_18.setGeometry(QtCore.QRect(30, 90, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_18.setFont(font)
        self.testexecute_page6_label_18.setObjectName("testexecute_page6_label_18")
        self.layoutWidget_10 = QtWidgets.QWidget(self.testexecute_page6)
        self.layoutWidget_10.setGeometry(QtCore.QRect(30, 50, 375, 33))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.layoutWidget_10)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.testexecute_page6_checkBox_com9 = QtWidgets.QCheckBox(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.testexecute_page6_checkBox_com9.setFont(font)
        self.testexecute_page6_checkBox_com9.setObjectName("testexecute_page6_checkBox_com9")
        self.gridLayout_24.addWidget(self.testexecute_page6_checkBox_com9, 0, 0, 1, 1)
        self.layoutWidget_11 = QtWidgets.QWidget(self.testexecute_page6)
        self.layoutWidget_11.setGeometry(QtCore.QRect(30, 110, 503, 35))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.layoutWidget_11)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.testexecute_page6_label_19 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_19.setFont(font)
        self.testexecute_page6_label_19.setObjectName("testexecute_page6_label_19")
        self.gridLayout_25.addWidget(self.testexecute_page6_label_19, 0, 0, 1, 1)
        self.testexecute_page6_lineEdit_local_ip = QtWidgets.QLineEdit(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page6_lineEdit_local_ip.setFont(font)
        self.testexecute_page6_lineEdit_local_ip.setObjectName("testexecute_page6_lineEdit_local_ip")
        self.gridLayout_25.addWidget(self.testexecute_page6_lineEdit_local_ip, 0, 1, 1, 1)
        self.testexecute_page6_label_20 = QtWidgets.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_20.setFont(font)
        self.testexecute_page6_label_20.setObjectName("testexecute_page6_label_20")
        self.gridLayout_25.addWidget(self.testexecute_page6_label_20, 0, 2, 1, 1)
        self.testexecute_page6_lineEdit_local_port = QtWidgets.QLineEdit(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page6_lineEdit_local_port.setFont(font)
        self.testexecute_page6_lineEdit_local_port.setObjectName("testexecute_page6_lineEdit_local_port")
        self.gridLayout_25.addWidget(self.testexecute_page6_lineEdit_local_port, 0, 3, 1, 1)
        self.testexecute_page6_label_21 = QtWidgets.QLabel(self.testexecute_page6)
        self.testexecute_page6_label_21.setGeometry(QtCore.QRect(20, 0, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_21.setFont(font)
        self.testexecute_page6_label_21.setObjectName("testexecute_page6_label_21")
        self.layoutWidget_12 = QtWidgets.QWidget(self.testexecute_page6)
        self.layoutWidget_12.setGeometry(QtCore.QRect(800, 150, 195, 41))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.layoutWidget_12)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.testexecute_page6_pushButton_execute = QtWidgets.QPushButton(self.layoutWidget_12)
        self.testexecute_page6_pushButton_execute.setObjectName("testexecute_page6_pushButton_execute")
        self.gridLayout_26.addWidget(self.testexecute_page6_pushButton_execute, 0, 0, 1, 1)
        self.testexecute_page6_pushButton_savedata = QtWidgets.QPushButton(self.layoutWidget_12)
        self.testexecute_page6_pushButton_savedata.setObjectName("testexecute_page6_pushButton_savedata")
        self.gridLayout_26.addWidget(self.testexecute_page6_pushButton_savedata, 0, 1, 1, 1)
        self.testexecute_page6_pushButton_local_disconnet = QtWidgets.QPushButton(self.testexecute_page6)
        self.testexecute_page6_pushButton_local_disconnet.setGeometry(QtCore.QRect(540, 110, 93, 29))
        self.testexecute_page6_pushButton_local_disconnet.setObjectName("testexecute_page6_pushButton_local_disconnet")
        self.layoutWidget_13 = QtWidgets.QWidget(self.testexecute_page6)
        self.layoutWidget_13.setGeometry(QtCore.QRect(30, 150, 503, 35))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.layoutWidget_13)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.testexecute_page6_label_22 = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_22.setFont(font)
        self.testexecute_page6_label_22.setObjectName("testexecute_page6_label_22")
        self.gridLayout_27.addWidget(self.testexecute_page6_label_22, 0, 0, 1, 1)
        self.testexecute_page6_lineEdit_remote_ip = QtWidgets.QLineEdit(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page6_lineEdit_remote_ip.setFont(font)
        self.testexecute_page6_lineEdit_remote_ip.setObjectName("testexecute_page6_lineEdit_remote_ip")
        self.gridLayout_27.addWidget(self.testexecute_page6_lineEdit_remote_ip, 0, 1, 1, 1)
        self.testexecute_page6_label_23 = QtWidgets.QLabel(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_23.setFont(font)
        self.testexecute_page6_label_23.setObjectName("testexecute_page6_label_23")
        self.gridLayout_27.addWidget(self.testexecute_page6_label_23, 0, 2, 1, 1)
        self.testexecute_page6_lineEdit_remote_port = QtWidgets.QLineEdit(self.layoutWidget_13)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.testexecute_page6_lineEdit_remote_port.setFont(font)
        self.testexecute_page6_lineEdit_remote_port.setObjectName("testexecute_page6_lineEdit_remote_port")
        self.gridLayout_27.addWidget(self.testexecute_page6_lineEdit_remote_port, 0, 3, 1, 1)
        self.testexecute_page6_label_24 = QtWidgets.QLabel(self.testexecute_page6)
        self.testexecute_page6_label_24.setGeometry(QtCore.QRect(30, 30, 153, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.testexecute_page6_label_24.setFont(font)
        self.testexecute_page6_label_24.setObjectName("testexecute_page6_label_24")
        self.testexecute_page6_pushButton_remote_link = QtWidgets.QPushButton(self.testexecute_page6)
        self.testexecute_page6_pushButton_remote_link.setGeometry(QtCore.QRect(540, 150, 93, 29))
        self.testexecute_page6_pushButton_remote_link.setObjectName("testexecute_page6_pushButton_remote_link")
        self.stackedWidget_testexecute.addWidget(self.testexecute_page6)
        self.stackedWidget.addWidget(self.page_testexecute)
        self.pageTestData = QtWidgets.QWidget()
        self.pageTestData.setObjectName("pageTestData")
        self.pushButton_TestData_export = QtWidgets.QPushButton(self.pageTestData)
        self.pushButton_TestData_export.setGeometry(QtCore.QRect(860, 100, 111, 31))
        self.pushButton_TestData_export.setObjectName("pushButton_TestData_export")
        self.pushButton_TestData_upload = QtWidgets.QPushButton(self.pageTestData)
        self.pushButton_TestData_upload.setGeometry(QtCore.QRect(860, 150, 111, 31))
        self.pushButton_TestData_upload.setObjectName("pushButton_TestData_upload")
        self.test_data_tableWidget = QtWidgets.QTableWidget(self.pageTestData)
        self.test_data_tableWidget.setGeometry(QtCore.QRect(20, 80, 831, 411))
        self.test_data_tableWidget.setMinimumSize(QtCore.QSize(250, 0))
        self.test_data_tableWidget.setObjectName("test_data_tableWidget")
        self.test_data_tableWidget.setColumnCount(7)
        self.test_data_tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_data_tableWidget.setItem(4, 5, item)
        self.label_4 = QtWidgets.QLabel(self.pageTestData)
        self.label_4.setGeometry(QtCore.QRect(390, 20, 84, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.pageTestData)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.label_sytem_test_procedure_label = QtWidgets.QLabel(Dialog)
        self.label_sytem_test_procedure_label.setGeometry(QtCore.QRect(70, 0, 191, 31))
        self.label_sytem_test_procedure_label.setObjectName("label_sytem_test_procedure_label")
        self.label_label_sytem_test_procedure = QtWidgets.QLabel(Dialog)
        self.label_label_sytem_test_procedure.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.label_label_sytem_test_procedure.setObjectName("label_label_sytem_test_procedure")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_4 = QtWidgets.QSplitter(Dialog)
        self.splitter_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setGeometry(QtCore.QRect(840, 1, 132, 39))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_last = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_last.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.pushButton_last.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon/last4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_last.setIcon(icon)
        self.pushButton_last.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_last.setObjectName("pushButton_last")
        self.pushButton_next = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_next.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/icon/next4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_next.setIcon(icon1)
        self.pushButton_next.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_next.setObjectName("pushButton_next")
        self.pushButton_close = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_close.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.pushButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/icon/close4.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_close.setIcon(icon2)
        self.pushButton_close.setIconSize(QtCore.QSize(32, 31))
        self.pushButton_close.setObjectName("pushButton_close")

        self.retranslateUi(Dialog)
        self.stackedWidget_testexecute.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_disassemble_previous.setText(_translate("Dialog", "上一步"))
        self.pushButton_disassemble_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testdevice_previous.setText(_translate("Dialog", "上一步"))
        self.pushButton_testdevice_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testexecute_next.setText(_translate("Dialog", "下一步"))
        self.pushButton_testexecute_last.setText(_translate("Dialog", "上一步"))
        self.testexecute_page1_label.setText(_translate("Dialog", "保险丝测试"))
        self.testexecute_page2_label.setText(_translate("Dialog", "电源部分测试"))
        self.testexecute_page3_label_2.setText(_translate("Dialog", "网络协议转换板测试"))
        self.testexecute_page3_label_3.setText(_translate("Dialog", "测试端口"))
        self.testexecute_page3_checkBox_lan2.setText(_translate("Dialog", "LAN2"))
        self.testexecute_page3_checkBox_lan3.setText(_translate("Dialog", "LAN3"))
        self.testexecute_page3_checkBox_lan4.setText(_translate("Dialog", "LAN4"))
        self.testexecute_page3_checkBox_lan5.setText(_translate("Dialog", "LAN5"))
        self.testexecute_page3_checkBox_lan6.setText(_translate("Dialog", "LAN6"))
        self.testexecute_page3_checkBox_lan7.setText(_translate("Dialog", "LAN7"))
        self.testexecute_page3_checkBox_lan8.setText(_translate("Dialog", "LAN8"))
        self.groupBox.setTitle(_translate("Dialog", "测试说明"))
        self.groupBox_2.setTitle(_translate("Dialog", "测试结果"))
        self.testexecute_page3_pushButton_execute.setText(_translate("Dialog", "测试"))
        self.testexecute_page3_pushButton_savedata.setText(_translate("Dialog", "保存数据"))
        self.testexecute_page4_label_4.setText(_translate("Dialog", "协议转换与控制测试：COM1-COM4"))
        self.groupBox_3.setTitle(_translate("Dialog", "测试说明"))
        self.groupBox_4.setTitle(_translate("Dialog", "测试结果"))
        self.testexecute_page4_label_5.setText(_translate("Dialog", "测试端口"))
        self.testexecute_page4_label_10.setText(_translate("Dialog", "测试配置"))
        self.testexecute_page4_label_8.setText(_translate("Dialog", "远程IP"))
        self.testexecute_page4_label_9.setText(_translate("Dialog", "端口"))
        self.testexecute_page4_pushButton_execute.setText(_translate("Dialog", "测试"))
        self.testexecute_page4_pushButton_savedata.setText(_translate("Dialog", "保存数据"))
        self.testexecute_page4_pushButton_local_disconnect.setText(_translate("Dialog", "断开"))
        self.testexecute_page4_pushButton_remote_link.setText(_translate("Dialog", "连接"))
        self.testexecute_page4_checkBox_com1.setText(_translate("Dialog", "COM1"))
        self.testexecute_page4_checkBox_com2.setText(_translate("Dialog", "COM2"))
        self.testexecute_page4_checkBox_com3.setText(_translate("Dialog", "COM3"))
        self.testexecute_page4_checkBox_com4.setText(_translate("Dialog", "COM4"))
        self.testexecute_page4_label_6.setText(_translate("Dialog", "本地IP"))
        self.testexecute_page4_label_7.setText(_translate("Dialog", "端口"))
        self.groupBox_5.setTitle(_translate("Dialog", "测试说明"))
        self.groupBox_6.setTitle(_translate("Dialog", "测试结果"))
        self.testexecute_page5_label_11.setText(_translate("Dialog", "测试配置"))
        self.testexecute_page5_checkBox_com5.setText(_translate("Dialog", "COM5"))
        self.testexecute_page5_checkBox_com6.setText(_translate("Dialog", "COM6"))
        self.testexecute_page5_checkBox_com7.setText(_translate("Dialog", "COM7"))
        self.testexecute_page5_checkBox_com8.setText(_translate("Dialog", "COM8"))
        self.testexecute_page5_label_12.setText(_translate("Dialog", "本地IP"))
        self.testexecute_page5_label_13.setText(_translate("Dialog", "端口"))
        self.testexecute_page5_label_14.setText(_translate("Dialog", "协议转换与控制测试：COM5-COM8"))
        self.testexecute_page5_pushButton_execute.setText(_translate("Dialog", "测试"))
        self.testexecute_page5_pushButton_savedata.setText(_translate("Dialog", "保存数据"))
        self.testexecute_page5_pushButton_local_disconnect.setText(_translate("Dialog", "断开"))
        self.testexecute_page5_label_15.setText(_translate("Dialog", "远程IP"))
        self.testexecute_page5_label_16.setText(_translate("Dialog", "端口"))
        self.testexecute_page5_label_17.setText(_translate("Dialog", "测试端口"))
        self.testexecute_page5_pushButton_remote_link.setText(_translate("Dialog", "连接"))
        self.groupBox_7.setTitle(_translate("Dialog", "测试说明"))
        self.groupBox_8.setTitle(_translate("Dialog", "测试结果"))
        self.testexecute_page6_label_18.setText(_translate("Dialog", "测试配置"))
        self.testexecute_page6_checkBox_com9.setText(_translate("Dialog", "COM9"))
        self.testexecute_page6_label_19.setText(_translate("Dialog", "本地IP"))
        self.testexecute_page6_label_20.setText(_translate("Dialog", "端口"))
        self.testexecute_page6_label_21.setText(_translate("Dialog", "协议转换与控制测试：COM9"))
        self.testexecute_page6_pushButton_execute.setText(_translate("Dialog", "测试"))
        self.testexecute_page6_pushButton_savedata.setText(_translate("Dialog", "保存数据"))
        self.testexecute_page6_pushButton_local_disconnet.setText(_translate("Dialog", "断开"))
        self.testexecute_page6_label_22.setText(_translate("Dialog", "远程IP"))
        self.testexecute_page6_label_23.setText(_translate("Dialog", "端口"))
        self.testexecute_page6_label_24.setText(_translate("Dialog", "测试端口"))
        self.testexecute_page6_pushButton_remote_link.setText(_translate("Dialog", "连接"))
        self.pushButton_TestData_export.setText(_translate("Dialog", "数据导出"))
        self.pushButton_TestData_upload.setText(_translate("Dialog", "数据上传"))
        item = self.test_data_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.test_data_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.test_data_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.test_data_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.test_data_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.test_data_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "交换机型号"))
        item = self.test_data_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Com1"))
        item = self.test_data_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Com2"))
        item = self.test_data_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "测试指标"))
        item = self.test_data_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "丢包数"))
        item = self.test_data_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "测试结果"))
        __sortingEnabled = self.test_data_tableWidget.isSortingEnabled()
        self.test_data_tableWidget.setSortingEnabled(False)
        item = self.test_data_tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "LAN1"))
        item = self.test_data_tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "LAN2"))
        item = self.test_data_tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(0, 4)
        item.setText(_translate("Dialog", "10"))
        item = self.test_data_tableWidget.item(0, 5)
        item.setText(_translate("Dialog", "通过"))
        item = self.test_data_tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "LAN3"))
        item = self.test_data_tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "LAN4"))
        item = self.test_data_tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(1, 4)
        item.setText(_translate("Dialog", "103"))
        item = self.test_data_tableWidget.item(1, 5)
        item.setText(_translate("Dialog", "不通过"))
        item = self.test_data_tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "LAN6"))
        item = self.test_data_tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "LAN7"))
        item = self.test_data_tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(2, 4)
        item.setText(_translate("Dialog", "56"))
        item = self.test_data_tableWidget.item(2, 5)
        item.setText(_translate("Dialog", "通过"))
        item = self.test_data_tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "LAN8"))
        item = self.test_data_tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "LAN9"))
        item = self.test_data_tableWidget.item(3, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(3, 4)
        item.setText(_translate("Dialog", "23"))
        item = self.test_data_tableWidget.item(3, 5)
        item.setText(_translate("Dialog", "通过"))
        item = self.test_data_tableWidget.item(4, 0)
        item.setText(_translate("Dialog", "ECOM-NS-2"))
        item = self.test_data_tableWidget.item(4, 1)
        item.setText(_translate("Dialog", "LAN10"))
        item = self.test_data_tableWidget.item(4, 2)
        item.setText(_translate("Dialog", "LAN11"))
        item = self.test_data_tableWidget.item(4, 3)
        item.setText(_translate("Dialog", "流量带宽1000M，包长128bytes，测试时间60s"))
        item = self.test_data_tableWidget.item(4, 4)
        item.setText(_translate("Dialog", "76"))
        item = self.test_data_tableWidget.item(4, 5)
        item.setText(_translate("Dialog", "通过"))
        self.test_data_tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("Dialog", "测试数据管理"))
        self.label_sytem_test_procedure_label.setText(_translate("Dialog", "系统拆机演示"))
        self.label_label_sytem_test_procedure.setText(_translate("Dialog", "测试流程："))
import res.iconQrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
